universe            = vanilla

# run inside the EL7 container (CMSSW_10_6_28 is slc7-built)
+MySingularityImage = "/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/el7:x86_64"
+MySingularityArgs  = "--bind /tmp:/tmp"

executable          = dilutionMap.sh
output              = condorOut/dilutionMap.out
error               = condorOut/dilutionMap.err
log                 = condorOut/dilutionMap.log

RequestCpus         = 1
RequestMemory       = 4 GB
RequestDisk         = 4 GB
+RequestRuntime     = 172800

queue