#pragma once

#include "UHH2/core/include/Hists.h"
#include "UHH2/core/include/Event.h"
#include "UHH2/ZprimeSemiLeptonic/include/ZprimeSemiLeptonicModules.h"

#include <UHH2/common/include/TTbarGen.h>
#include <UHH2/common/include/TTbarReconstruction.h>
#include <UHH2/common/include/ReconstructionHypothesisDiscriminators.h>

#include <TLorentzVector.h>
#include <string>
#include <map>
#include <memory>
#include <vector>

class ZprimeSemiLeptonicSystematicsHists: public uhh2::Hists {
public:
  explicit ZprimeSemiLeptonicSystematicsHists(uhh2::Context&, const std::string&);
  virtual void fill(const uhh2::Event&) override;

protected:
  void init();
  bool is_mc, is_Muon;
  bool is_tt, ishotvr, isdeepAK8;
  bool isMuon;
  bool isElectron;
  bool debug;

  // electron systematics: reco, id, trigger
  uhh2::Event::Handle<float> h_ele_reco;
  uhh2::Event::Handle<float> h_ele_reco_up;
  uhh2::Event::Handle<float> h_ele_reco_down;
  uhh2::Event::Handle<float> h_ele_id;
  uhh2::Event::Handle<float> h_ele_id_up;
  uhh2::Event::Handle<float> h_ele_id_down;
  uhh2::Event::Handle<float> h_ele_trigger;
  uhh2::Event::Handle<float> h_ele_trigger_up;
  uhh2::Event::Handle<float> h_ele_trigger_down;
  // muon systematics: reco, id_stat, id_syst, trigger_stat, trigger_syst, iso_stat, iso_syst
  uhh2::Event::Handle<float> h_mu_reco;
  uhh2::Event::Handle<float> h_mu_reco_up;
  uhh2::Event::Handle<float> h_mu_reco_down;
  uhh2::Event::Handle<float> h_mu_iso_stat;
  uhh2::Event::Handle<float> h_mu_iso_stat_up;
  uhh2::Event::Handle<float> h_mu_iso_stat_down;
  uhh2::Event::Handle<float> h_mu_iso_syst;
  uhh2::Event::Handle<float> h_mu_iso_syst_up;
  uhh2::Event::Handle<float> h_mu_iso_syst_down;
  uhh2::Event::Handle<float> h_mu_id_stat;
  uhh2::Event::Handle<float> h_mu_id_stat_up;
  uhh2::Event::Handle<float> h_mu_id_stat_down;
  uhh2::Event::Handle<float> h_mu_id_syst;
  uhh2::Event::Handle<float> h_mu_id_syst_up;
  uhh2::Event::Handle<float> h_mu_id_syst_down;
  uhh2::Event::Handle<float> h_mu_trigger_stat;
  uhh2::Event::Handle<float> h_mu_trigger_stat_up;
  uhh2::Event::Handle<float> h_mu_trigger_stat_down;
  uhh2::Event::Handle<float> h_mu_trigger_syst;
  uhh2::Event::Handle<float> h_mu_trigger_syst_up;
  uhh2::Event::Handle<float> h_mu_trigger_syst_down;
  // Pileup reweighting systematics
  uhh2::Event::Handle<float> h_pu;
  uhh2::Event::Handle<float> h_pu_up;
  uhh2::Event::Handle<float> h_pu_down;
  // Prefiring systematics
  uhh2::Event::Handle<float> h_prefiring;
  uhh2::Event::Handle<float> h_prefiring_up;
  uhh2::Event::Handle<float> h_prefiring_down;
  // b-tagging systematics: central, cferr1, cferr2, hf, hfstats1, hfstats2, lf, lfstats1, lfstats2
  uhh2::Event::Handle<float> h_btag;
  uhh2::Event::Handle<float> h_btag_cferr1_up;
  uhh2::Event::Handle<float> h_btag_cferr1_down;
  uhh2::Event::Handle<float> h_btag_cferr2_up;
  uhh2::Event::Handle<float> h_btag_cferr2_down;
  uhh2::Event::Handle<float> h_btag_hf_up;
  uhh2::Event::Handle<float> h_btag_hf_down;
  uhh2::Event::Handle<float> h_btag_hfstats1_up;
  uhh2::Event::Handle<float> h_btag_hfstats1_down;
  uhh2::Event::Handle<float> h_btag_hfstats2_up;
  uhh2::Event::Handle<float> h_btag_hfstats2_down;
  uhh2::Event::Handle<float> h_btag_lf_up;
  uhh2::Event::Handle<float> h_btag_lf_down;
  uhh2::Event::Handle<float> h_btag_lfstats1_up;
  uhh2::Event::Handle<float> h_btag_lfstats1_down;
  uhh2::Event::Handle<float> h_btag_lfstats2_up;
  uhh2::Event::Handle<float> h_btag_lfstats2_down;
  // Top tagging systematics
  uhh2::Event::Handle<float> h_ttag;
  uhh2::Event::Handle<float> h_ttag_corr_up;
  uhh2::Event::Handle<float> h_ttag_corr_down;
  uhh2::Event::Handle<float> h_ttag_uncorr_up;
  uhh2::Event::Handle<float> h_ttag_uncorr_down;
  // Top mistagging systematics
  uhh2::Event::Handle<float> h_tmistag;
  uhh2::Event::Handle<float> h_tmistag_up;
  uhh2::Event::Handle<float> h_tmistag_down;
  // Top pT reweighting systematics
  uhh2::Event::Handle<float> h_toppt_a_up;
  uhh2::Event::Handle<float> h_toppt_a_down;
  uhh2::Event::Handle<float> h_toppt_b_up;
  uhh2::Event::Handle<float> h_toppt_b_down;
  // muR and muF at ME level systematics
  uhh2::Event::Handle<float> h_murmuf_upup;
  uhh2::Event::Handle<float> h_murmuf_upnone;
  uhh2::Event::Handle<float> h_murmuf_noneup;
  uhh2::Event::Handle<float> h_murmuf_nonedown;
  uhh2::Event::Handle<float> h_murmuf_downnone;
  uhh2::Event::Handle<float> h_murmuf_downdown;
  // ISR and FSR systematics
  uhh2::Event::Handle<float> h_isr_up;
  uhh2::Event::Handle<float> h_isr_down;
  uhh2::Event::Handle<float> h_fsr_up;
  uhh2::Event::Handle<float> h_fsr_down;

  
  // DeltaY histograms
  TH1F *DeltaY;
  TH1F *DeltaY_mu_reco_up;
  TH1F *DeltaY_mu_reco_down;
  TH1F *DeltaY_pu_up;
  TH1F *DeltaY_pu_down;
  TH1F *DeltaY_prefiring_up;
  TH1F *DeltaY_prefiring_down;
  TH1F *DeltaY_mu_iso_stat_up;
  TH1F *DeltaY_mu_iso_stat_down;
  TH1F *DeltaY_mu_iso_syst_up;
  TH1F *DeltaY_mu_iso_syst_down;
  TH1F *DeltaY_mu_id_stat_up;
  TH1F *DeltaY_mu_id_stat_down;
  TH1F *DeltaY_mu_id_syst_up;
  TH1F *DeltaY_mu_id_syst_down;
  TH1F *DeltaY_mu_trigger_stat_up;
  TH1F *DeltaY_mu_trigger_stat_down;
  TH1F *DeltaY_mu_trigger_syst_up;
  TH1F *DeltaY_mu_trigger_syst_down;
  TH1F *DeltaY_ele_id_up;
  TH1F *DeltaY_ele_id_down;
  TH1F *DeltaY_ele_trigger_up;
  TH1F *DeltaY_ele_trigger_down;
  TH1F *DeltaY_ele_reco_up;
  TH1F *DeltaY_ele_reco_down;
  TH1F *DeltaY_murmuf_upup;
  TH1F *DeltaY_murmuf_upnone;
  TH1F *DeltaY_murmuf_noneup;
  TH1F *DeltaY_murmuf_nonedown;
  TH1F *DeltaY_murmuf_downnone;
  TH1F *DeltaY_murmuf_downdown;
  TH1F *DeltaY_isr_up;
  TH1F *DeltaY_isr_down;
  TH1F *DeltaY_fsr_up;
  TH1F *DeltaY_fsr_down;
  TH1F *DeltaY_btag_cferr1_up;
  TH1F *DeltaY_btag_cferr1_down;
  TH1F *DeltaY_btag_cferr2_up;
  TH1F *DeltaY_btag_cferr2_down;
  TH1F *DeltaY_btag_hf_up;
  TH1F *DeltaY_btag_hf_down;
  TH1F *DeltaY_btag_hfstats1_up;
  TH1F *DeltaY_btag_hfstats1_down;
  TH1F *DeltaY_btag_hfstats2_up;
  TH1F *DeltaY_btag_hfstats2_down;
  TH1F *DeltaY_btag_lf_up;
  TH1F *DeltaY_btag_lf_down;
  TH1F *DeltaY_btag_lfstats1_up;
  TH1F *DeltaY_btag_lfstats1_down;
  TH1F *DeltaY_btag_lfstats2_up;
  TH1F *DeltaY_btag_lfstats2_down;
  TH1F *DeltaY_ttag_corr_up;
  TH1F *DeltaY_ttag_corr_down;
  TH1F *DeltaY_ttag_uncorr_up;
  TH1F *DeltaY_ttag_uncorr_down;
  TH1F *DeltaY_tmistag_up;
  TH1F *DeltaY_tmistag_down;
  TH1F *DeltaY_toppt_a_up;
  TH1F *DeltaY_toppt_a_down;
  TH1F *DeltaY_toppt_b_up;
  TH1F *DeltaY_toppt_b_down;

  // LEGACY: Unfolding matrix
  TH2F *DeltaY_tt;
  TH2F *DeltaY_mu_reco_up_tt;
  TH2F *DeltaY_mu_reco_down_tt;
  TH2F *DeltaY_pu_up_tt;
  TH2F *DeltaY_pu_down_tt;
  TH2F *DeltaY_prefiring_up_tt;
  TH2F *DeltaY_prefiring_down_tt;
  TH2F *DeltaY_mu_id_stat_up_tt;
  TH2F *DeltaY_mu_id_stat_down_tt;
  TH2F *DeltaY_mu_id_syst_up_tt;
  TH2F *DeltaY_mu_id_syst_down_tt;
  TH2F *DeltaY_mu_iso_stat_up_tt;
  TH2F *DeltaY_mu_iso_stat_down_tt;
  TH2F *DeltaY_mu_iso_syst_up_tt;
  TH2F *DeltaY_mu_iso_syst_down_tt;
  TH2F *DeltaY_mu_trigger_stat_up_tt;
  TH2F *DeltaY_mu_trigger_stat_down_tt;
  TH2F *DeltaY_mu_trigger_syst_up_tt;
  TH2F *DeltaY_mu_trigger_syst_down_tt;
  TH2F *DeltaY_ele_id_up_tt;
  TH2F *DeltaY_ele_id_down_tt;
  TH2F *DeltaY_ele_trigger_up_tt;
  TH2F *DeltaY_ele_trigger_down_tt;
  TH2F *DeltaY_ele_reco_up_tt;
  TH2F *DeltaY_ele_reco_down_tt;
  TH2F *DeltaY_murmuf_upup_tt;
  TH2F *DeltaY_murmuf_upnone_tt;
  TH2F *DeltaY_murmuf_noneup_tt;
  TH2F *DeltaY_murmuf_nonedown_tt;
  TH2F *DeltaY_murmuf_downnone_tt;
  TH2F *DeltaY_murmuf_downdown_tt;
  TH2F *DeltaY_isr_up_tt;
  TH2F *DeltaY_isr_down_tt;
  TH2F *DeltaY_fsr_up_tt;
  TH2F *DeltaY_fsr_down_tt;
  TH2F *DeltaY_btag_cferr1_up_tt;
  TH2F *DeltaY_btag_cferr1_down_tt;
  TH2F *DeltaY_btag_cferr2_up_tt;
  TH2F *DeltaY_btag_cferr2_down_tt;
  TH2F *DeltaY_btag_hf_up_tt;
  TH2F *DeltaY_btag_hf_down_tt;
  TH2F *DeltaY_btag_hfstats1_up_tt;
  TH2F *DeltaY_btag_hfstats1_down_tt;
  TH2F *DeltaY_btag_hfstats2_up_tt;
  TH2F *DeltaY_btag_hfstats2_down_tt;
  TH2F *DeltaY_btag_lf_up_tt;
  TH2F *DeltaY_btag_lf_down_tt;
  TH2F *DeltaY_btag_lfstats1_up_tt;
  TH2F *DeltaY_btag_lfstats1_down_tt;
  TH2F *DeltaY_btag_lfstats2_up_tt;
  TH2F *DeltaY_btag_lfstats2_down_tt;
  TH2F *DeltaY_ttag_corr_up_tt;
  TH2F *DeltaY_ttag_corr_down_tt;
  TH2F *DeltaY_ttag_uncorr_up_tt;
  TH2F *DeltaY_ttag_uncorr_down_tt;
  TH2F *DeltaY_tmistag_up_tt;
  TH2F *DeltaY_tmistag_down_tt;
  TH2F *DeltaY_toppt_a_up_tt;
  TH2F *DeltaY_toppt_a_down_tt;
  TH2F *DeltaY_toppt_b_up_tt;
  TH2F *DeltaY_toppt_b_down_tt;

  // --- Template method: xi = tanh(DeltaY), multiple binning schemes ---
  TH1F *DeltaY_xi_reco_6;
  TH1F *DeltaY_xi_reco_12;
  TH1F *DeltaY_xi_reco_18;
  TH1F *DeltaY_xi_reco_24;
  TH1F *DeltaY_xi_reco_30;
  TH1F *DeltaY_xi_reco_36;
  TH1F *DeltaY_xi_reco_50;
  // NoAC systematics (f=+1 is Down, f=-1 is Up) - all binning schemes
  TH1F *DeltaY_xi_reco_6_NoAC_up;
  TH1F *DeltaY_xi_reco_6_NoAC_down;
  TH1F *DeltaY_xi_reco_12_NoAC_up;
  TH1F *DeltaY_xi_reco_12_NoAC_down;
  TH1F *DeltaY_xi_reco_18_NoAC_up;
  TH1F *DeltaY_xi_reco_18_NoAC_down;
  TH1F *DeltaY_xi_reco_24_NoAC_up;
  TH1F *DeltaY_xi_reco_24_NoAC_down;
  TH1F *DeltaY_xi_reco_30_NoAC_up;
  TH1F *DeltaY_xi_reco_30_NoAC_down;
  TH1F *DeltaY_xi_reco_36_NoAC_up;
  TH1F *DeltaY_xi_reco_36_NoAC_down;
  TH1F *DeltaY_xi_reco_50_NoAC_up;
  TH1F *DeltaY_xi_reco_50_NoAC_down;
  // NoAC systematics for f=±2, ±8, ±12 - all binning schemes
  TH1F *DeltaY_xi_reco_6_NoAC_up_f2;   TH1F *DeltaY_xi_reco_6_NoAC_down_f2;
  TH1F *DeltaY_xi_reco_6_NoAC_up_f8;   TH1F *DeltaY_xi_reco_6_NoAC_down_f8;
  TH1F *DeltaY_xi_reco_6_NoAC_up_f12;  TH1F *DeltaY_xi_reco_6_NoAC_down_f12;
  TH1F *DeltaY_xi_reco_12_NoAC_up_f2;  TH1F *DeltaY_xi_reco_12_NoAC_down_f2;
  TH1F *DeltaY_xi_reco_12_NoAC_up_f8;  TH1F *DeltaY_xi_reco_12_NoAC_down_f8;
  TH1F *DeltaY_xi_reco_12_NoAC_up_f12; TH1F *DeltaY_xi_reco_12_NoAC_down_f12;
  TH1F *DeltaY_xi_reco_18_NoAC_up_f2;  TH1F *DeltaY_xi_reco_18_NoAC_down_f2;
  TH1F *DeltaY_xi_reco_18_NoAC_up_f8;  TH1F *DeltaY_xi_reco_18_NoAC_down_f8;
  TH1F *DeltaY_xi_reco_18_NoAC_up_f12; TH1F *DeltaY_xi_reco_18_NoAC_down_f12;
  TH1F *DeltaY_xi_reco_24_NoAC_up_f2;  TH1F *DeltaY_xi_reco_24_NoAC_down_f2;
  TH1F *DeltaY_xi_reco_24_NoAC_up_f8;  TH1F *DeltaY_xi_reco_24_NoAC_down_f8;
  TH1F *DeltaY_xi_reco_24_NoAC_up_f12; TH1F *DeltaY_xi_reco_24_NoAC_down_f12;
  TH1F *DeltaY_xi_reco_30_NoAC_up_f2;  TH1F *DeltaY_xi_reco_30_NoAC_down_f2;
  TH1F *DeltaY_xi_reco_30_NoAC_up_f8;  TH1F *DeltaY_xi_reco_30_NoAC_down_f8;
  TH1F *DeltaY_xi_reco_30_NoAC_up_f12; TH1F *DeltaY_xi_reco_30_NoAC_down_f12;
  TH1F *DeltaY_xi_reco_36_NoAC_up_f2;  TH1F *DeltaY_xi_reco_36_NoAC_down_f2;
  TH1F *DeltaY_xi_reco_36_NoAC_up_f8;  TH1F *DeltaY_xi_reco_36_NoAC_down_f8;
  TH1F *DeltaY_xi_reco_36_NoAC_up_f12; TH1F *DeltaY_xi_reco_36_NoAC_down_f12;
  TH1F *DeltaY_xi_reco_50_NoAC_up_f2;  TH1F *DeltaY_xi_reco_50_NoAC_down_f2;
  TH1F *DeltaY_xi_reco_50_NoAC_up_f8;  TH1F *DeltaY_xi_reco_50_NoAC_down_f8;
  TH1F *DeltaY_xi_reco_50_NoAC_up_f12; TH1F *DeltaY_xi_reco_50_NoAC_down_f12;
  // lepton/trigger/pileup/prefiring - 6 bins
  TH1F *DeltaY_xi_reco_6_ele_reco_up;      TH1F *DeltaY_xi_reco_6_ele_reco_down;
  TH1F *DeltaY_xi_reco_6_ele_id_up;        TH1F *DeltaY_xi_reco_6_ele_id_down;
  TH1F *DeltaY_xi_reco_6_ele_trigger_up;   TH1F *DeltaY_xi_reco_6_ele_trigger_down;
  TH1F *DeltaY_xi_reco_6_mu_reco_up;       TH1F *DeltaY_xi_reco_6_mu_reco_down;
  TH1F *DeltaY_xi_reco_6_mu_iso_stat_up;   TH1F *DeltaY_xi_reco_6_mu_iso_stat_down;
  TH1F *DeltaY_xi_reco_6_mu_iso_syst_up;   TH1F *DeltaY_xi_reco_6_mu_iso_syst_down;
  TH1F *DeltaY_xi_reco_6_mu_id_stat_up;    TH1F *DeltaY_xi_reco_6_mu_id_stat_down;
  TH1F *DeltaY_xi_reco_6_mu_id_syst_up;    TH1F *DeltaY_xi_reco_6_mu_id_syst_down;
  TH1F *DeltaY_xi_reco_6_mu_trigger_stat_up; TH1F *DeltaY_xi_reco_6_mu_trigger_stat_down;
  TH1F *DeltaY_xi_reco_6_mu_trigger_syst_up; TH1F *DeltaY_xi_reco_6_mu_trigger_syst_down;
  TH1F *DeltaY_xi_reco_6_pu_up;            TH1F *DeltaY_xi_reco_6_pu_down;
  TH1F *DeltaY_xi_reco_6_prefiring_up;     TH1F *DeltaY_xi_reco_6_prefiring_down;
  // scales, isr fsr - 6 bins
  TH1F *DeltaY_xi_reco_6_murmuf_upup;      TH1F *DeltaY_xi_reco_6_murmuf_upnone;
  TH1F *DeltaY_xi_reco_6_murmuf_noneup;    TH1F *DeltaY_xi_reco_6_murmuf_nonedown;
  TH1F *DeltaY_xi_reco_6_murmuf_downnone;  TH1F *DeltaY_xi_reco_6_murmuf_downdown;
  TH1F *DeltaY_xi_reco_6_isr_up;           TH1F *DeltaY_xi_reco_6_isr_down;
  TH1F *DeltaY_xi_reco_6_fsr_up;           TH1F *DeltaY_xi_reco_6_fsr_down;
  // btag - 6 bins
  TH1F *DeltaY_xi_reco_6_btag_cferr1_up;   TH1F *DeltaY_xi_reco_6_btag_cferr1_down;
  TH1F *DeltaY_xi_reco_6_btag_cferr2_up;   TH1F *DeltaY_xi_reco_6_btag_cferr2_down;
  TH1F *DeltaY_xi_reco_6_btag_hf_up;       TH1F *DeltaY_xi_reco_6_btag_hf_down;
  TH1F *DeltaY_xi_reco_6_btag_hfstats1_up; TH1F *DeltaY_xi_reco_6_btag_hfstats1_down;
  TH1F *DeltaY_xi_reco_6_btag_hfstats2_up; TH1F *DeltaY_xi_reco_6_btag_hfstats2_down;
  TH1F *DeltaY_xi_reco_6_btag_lf_up;       TH1F *DeltaY_xi_reco_6_btag_lf_down;
  TH1F *DeltaY_xi_reco_6_btag_lfstats1_up; TH1F *DeltaY_xi_reco_6_btag_lfstats1_down;
  TH1F *DeltaY_xi_reco_6_btag_lfstats2_up; TH1F *DeltaY_xi_reco_6_btag_lfstats2_down;
  // ttag, mistag, toppt - 6 bins
  TH1F *DeltaY_xi_reco_6_ttag_corr_up;     TH1F *DeltaY_xi_reco_6_ttag_corr_down;
  TH1F *DeltaY_xi_reco_6_ttag_uncorr_up;   TH1F *DeltaY_xi_reco_6_ttag_uncorr_down;
  TH1F *DeltaY_xi_reco_6_tmistag_up;       TH1F *DeltaY_xi_reco_6_tmistag_down;
  TH1F *DeltaY_xi_reco_6_toppt_a_up;       TH1F *DeltaY_xi_reco_6_toppt_a_down;
  TH1F *DeltaY_xi_reco_6_toppt_b_up;       TH1F *DeltaY_xi_reco_6_toppt_b_down;

  // lepton/trigger/pileup/prefiring - 12 bins
  TH1F *DeltaY_xi_reco_12_ele_reco_up;      TH1F *DeltaY_xi_reco_12_ele_reco_down;
  TH1F *DeltaY_xi_reco_12_ele_id_up;        TH1F *DeltaY_xi_reco_12_ele_id_down;
  TH1F *DeltaY_xi_reco_12_ele_trigger_up;   TH1F *DeltaY_xi_reco_12_ele_trigger_down;
  TH1F *DeltaY_xi_reco_12_mu_reco_up;       TH1F *DeltaY_xi_reco_12_mu_reco_down;
  TH1F *DeltaY_xi_reco_12_mu_iso_stat_up;   TH1F *DeltaY_xi_reco_12_mu_iso_stat_down;
  TH1F *DeltaY_xi_reco_12_mu_iso_syst_up;   TH1F *DeltaY_xi_reco_12_mu_iso_syst_down;
  TH1F *DeltaY_xi_reco_12_mu_id_stat_up;    TH1F *DeltaY_xi_reco_12_mu_id_stat_down;
  TH1F *DeltaY_xi_reco_12_mu_id_syst_up;    TH1F *DeltaY_xi_reco_12_mu_id_syst_down;
  TH1F *DeltaY_xi_reco_12_mu_trigger_stat_up; TH1F *DeltaY_xi_reco_12_mu_trigger_stat_down;
  TH1F *DeltaY_xi_reco_12_mu_trigger_syst_up; TH1F *DeltaY_xi_reco_12_mu_trigger_syst_down;
  TH1F *DeltaY_xi_reco_12_pu_up;            TH1F *DeltaY_xi_reco_12_pu_down;
  TH1F *DeltaY_xi_reco_12_prefiring_up;     TH1F *DeltaY_xi_reco_12_prefiring_down;
  // scales, isr fsr - 12 bins
  TH1F *DeltaY_xi_reco_12_murmuf_upup;      TH1F *DeltaY_xi_reco_12_murmuf_upnone;
  TH1F *DeltaY_xi_reco_12_murmuf_noneup;    TH1F *DeltaY_xi_reco_12_murmuf_nonedown;
  TH1F *DeltaY_xi_reco_12_murmuf_downnone;  TH1F *DeltaY_xi_reco_12_murmuf_downdown;
  TH1F *DeltaY_xi_reco_12_isr_up;           TH1F *DeltaY_xi_reco_12_isr_down;
  TH1F *DeltaY_xi_reco_12_fsr_up;           TH1F *DeltaY_xi_reco_12_fsr_down;
  // btag - 12 bins
  TH1F *DeltaY_xi_reco_12_btag_cferr1_up;   TH1F *DeltaY_xi_reco_12_btag_cferr1_down;
  TH1F *DeltaY_xi_reco_12_btag_cferr2_up;   TH1F *DeltaY_xi_reco_12_btag_cferr2_down;
  TH1F *DeltaY_xi_reco_12_btag_hf_up;       TH1F *DeltaY_xi_reco_12_btag_hf_down;
  TH1F *DeltaY_xi_reco_12_btag_hfstats1_up; TH1F *DeltaY_xi_reco_12_btag_hfstats1_down;
  TH1F *DeltaY_xi_reco_12_btag_hfstats2_up; TH1F *DeltaY_xi_reco_12_btag_hfstats2_down;
  TH1F *DeltaY_xi_reco_12_btag_lf_up;       TH1F *DeltaY_xi_reco_12_btag_lf_down;
  TH1F *DeltaY_xi_reco_12_btag_lfstats1_up; TH1F *DeltaY_xi_reco_12_btag_lfstats1_down;
  TH1F *DeltaY_xi_reco_12_btag_lfstats2_up; TH1F *DeltaY_xi_reco_12_btag_lfstats2_down;
  // ttag, mistag, toppt - 12 bins
  TH1F *DeltaY_xi_reco_12_ttag_corr_up;     TH1F *DeltaY_xi_reco_12_ttag_corr_down;
  TH1F *DeltaY_xi_reco_12_ttag_uncorr_up;   TH1F *DeltaY_xi_reco_12_ttag_uncorr_down;
  TH1F *DeltaY_xi_reco_12_tmistag_up;       TH1F *DeltaY_xi_reco_12_tmistag_down;
  TH1F *DeltaY_xi_reco_12_toppt_a_up;       TH1F *DeltaY_xi_reco_12_toppt_a_down;
  TH1F *DeltaY_xi_reco_12_toppt_b_up;       TH1F *DeltaY_xi_reco_12_toppt_b_down;

  // lepton/trigger/pileup/prefiring - 50 bins
  TH1F *DeltaY_xi_reco_50_ele_reco_up;      TH1F *DeltaY_xi_reco_50_ele_reco_down;
  TH1F *DeltaY_xi_reco_50_ele_id_up;        TH1F *DeltaY_xi_reco_50_ele_id_down;
  TH1F *DeltaY_xi_reco_50_ele_trigger_up;   TH1F *DeltaY_xi_reco_50_ele_trigger_down;
  TH1F *DeltaY_xi_reco_50_mu_reco_up;       TH1F *DeltaY_xi_reco_50_mu_reco_down;
  TH1F *DeltaY_xi_reco_50_mu_iso_stat_up;   TH1F *DeltaY_xi_reco_50_mu_iso_stat_down;
  TH1F *DeltaY_xi_reco_50_mu_iso_syst_up;   TH1F *DeltaY_xi_reco_50_mu_iso_syst_down;
  TH1F *DeltaY_xi_reco_50_mu_id_stat_up;    TH1F *DeltaY_xi_reco_50_mu_id_stat_down;
  TH1F *DeltaY_xi_reco_50_mu_id_syst_up;    TH1F *DeltaY_xi_reco_50_mu_id_syst_down;
  TH1F *DeltaY_xi_reco_50_mu_trigger_stat_up; TH1F *DeltaY_xi_reco_50_mu_trigger_stat_down;
  TH1F *DeltaY_xi_reco_50_mu_trigger_syst_up; TH1F *DeltaY_xi_reco_50_mu_trigger_syst_down;
  TH1F *DeltaY_xi_reco_50_pu_up;            TH1F *DeltaY_xi_reco_50_pu_down;
  TH1F *DeltaY_xi_reco_50_prefiring_up;     TH1F *DeltaY_xi_reco_50_prefiring_down;
  // scales, isr fsr - 50 bins
  TH1F *DeltaY_xi_reco_50_murmuf_upup;      TH1F *DeltaY_xi_reco_50_murmuf_upnone;
  TH1F *DeltaY_xi_reco_50_murmuf_noneup;    TH1F *DeltaY_xi_reco_50_murmuf_nonedown;
  TH1F *DeltaY_xi_reco_50_murmuf_downnone;  TH1F *DeltaY_xi_reco_50_murmuf_downdown;
  TH1F *DeltaY_xi_reco_50_isr_up;           TH1F *DeltaY_xi_reco_50_isr_down;
  TH1F *DeltaY_xi_reco_50_fsr_up;           TH1F *DeltaY_xi_reco_50_fsr_down;
  // btag - 50 bins
  TH1F *DeltaY_xi_reco_50_btag_cferr1_up;   TH1F *DeltaY_xi_reco_50_btag_cferr1_down;
  TH1F *DeltaY_xi_reco_50_btag_cferr2_up;   TH1F *DeltaY_xi_reco_50_btag_cferr2_down;
  TH1F *DeltaY_xi_reco_50_btag_hf_up;       TH1F *DeltaY_xi_reco_50_btag_hf_down;
  TH1F *DeltaY_xi_reco_50_btag_hfstats1_up; TH1F *DeltaY_xi_reco_50_btag_hfstats1_down;
  TH1F *DeltaY_xi_reco_50_btag_hfstats2_up; TH1F *DeltaY_xi_reco_50_btag_hfstats2_down;
  TH1F *DeltaY_xi_reco_50_btag_lf_up;       TH1F *DeltaY_xi_reco_50_btag_lf_down;
  TH1F *DeltaY_xi_reco_50_btag_lfstats1_up; TH1F *DeltaY_xi_reco_50_btag_lfstats1_down;
  TH1F *DeltaY_xi_reco_50_btag_lfstats2_up; TH1F *DeltaY_xi_reco_50_btag_lfstats2_down;
  // ttag, mistag, toppt - 50 bins
  TH1F *DeltaY_xi_reco_50_ttag_corr_up;     TH1F *DeltaY_xi_reco_50_ttag_corr_down;
  TH1F *DeltaY_xi_reco_50_ttag_uncorr_up;   TH1F *DeltaY_xi_reco_50_ttag_uncorr_down;
  TH1F *DeltaY_xi_reco_50_tmistag_up;       TH1F *DeltaY_xi_reco_50_tmistag_down;
  TH1F *DeltaY_xi_reco_50_toppt_a_up;       TH1F *DeltaY_xi_reco_50_toppt_a_down;
  TH1F *DeltaY_xi_reco_50_toppt_b_up;       TH1F *DeltaY_xi_reco_50_toppt_b_down;

  // lepton/trigger/pileup/prefiring - 24 bins
  TH1F *DeltaY_xi_reco_24_ele_reco_up;      TH1F *DeltaY_xi_reco_24_ele_reco_down;
  TH1F *DeltaY_xi_reco_24_ele_id_up;        TH1F *DeltaY_xi_reco_24_ele_id_down;
  TH1F *DeltaY_xi_reco_24_ele_trigger_up;   TH1F *DeltaY_xi_reco_24_ele_trigger_down;
  TH1F *DeltaY_xi_reco_24_mu_reco_up;       TH1F *DeltaY_xi_reco_24_mu_reco_down;
  TH1F *DeltaY_xi_reco_24_mu_iso_stat_up;   TH1F *DeltaY_xi_reco_24_mu_iso_stat_down;
  TH1F *DeltaY_xi_reco_24_mu_iso_syst_up;   TH1F *DeltaY_xi_reco_24_mu_iso_syst_down;
  TH1F *DeltaY_xi_reco_24_mu_id_stat_up;    TH1F *DeltaY_xi_reco_24_mu_id_stat_down;
  TH1F *DeltaY_xi_reco_24_mu_id_syst_up;    TH1F *DeltaY_xi_reco_24_mu_id_syst_down;
  TH1F *DeltaY_xi_reco_24_mu_trigger_stat_up; TH1F *DeltaY_xi_reco_24_mu_trigger_stat_down;
  TH1F *DeltaY_xi_reco_24_mu_trigger_syst_up; TH1F *DeltaY_xi_reco_24_mu_trigger_syst_down;
  TH1F *DeltaY_xi_reco_24_pu_up;            TH1F *DeltaY_xi_reco_24_pu_down;
  TH1F *DeltaY_xi_reco_24_prefiring_up;     TH1F *DeltaY_xi_reco_24_prefiring_down;
  // scales, isr fsr - 24 bins
  TH1F *DeltaY_xi_reco_24_murmuf_upup;      TH1F *DeltaY_xi_reco_24_murmuf_upnone;
  TH1F *DeltaY_xi_reco_24_murmuf_noneup;    TH1F *DeltaY_xi_reco_24_murmuf_nonedown;
  TH1F *DeltaY_xi_reco_24_murmuf_downnone;  TH1F *DeltaY_xi_reco_24_murmuf_downdown;
  TH1F *DeltaY_xi_reco_24_isr_up;           TH1F *DeltaY_xi_reco_24_isr_down;
  TH1F *DeltaY_xi_reco_24_fsr_up;           TH1F *DeltaY_xi_reco_24_fsr_down;
  // btag - 24 bins
  TH1F *DeltaY_xi_reco_24_btag_cferr1_up;   TH1F *DeltaY_xi_reco_24_btag_cferr1_down;
  TH1F *DeltaY_xi_reco_24_btag_cferr2_up;   TH1F *DeltaY_xi_reco_24_btag_cferr2_down;
  TH1F *DeltaY_xi_reco_24_btag_hf_up;       TH1F *DeltaY_xi_reco_24_btag_hf_down;
  TH1F *DeltaY_xi_reco_24_btag_hfstats1_up; TH1F *DeltaY_xi_reco_24_btag_hfstats1_down;
  TH1F *DeltaY_xi_reco_24_btag_hfstats2_up; TH1F *DeltaY_xi_reco_24_btag_hfstats2_down;
  TH1F *DeltaY_xi_reco_24_btag_lf_up;       TH1F *DeltaY_xi_reco_24_btag_lf_down;
  TH1F *DeltaY_xi_reco_24_btag_lfstats1_up; TH1F *DeltaY_xi_reco_24_btag_lfstats1_down;
  TH1F *DeltaY_xi_reco_24_btag_lfstats2_up; TH1F *DeltaY_xi_reco_24_btag_lfstats2_down;
  // ttag, mistag, toppt - 24 bins
  TH1F *DeltaY_xi_reco_24_ttag_corr_up;     TH1F *DeltaY_xi_reco_24_ttag_corr_down;
  TH1F *DeltaY_xi_reco_24_ttag_uncorr_up;   TH1F *DeltaY_xi_reco_24_ttag_uncorr_down;
  TH1F *DeltaY_xi_reco_24_tmistag_up;       TH1F *DeltaY_xi_reco_24_tmistag_down;
  TH1F *DeltaY_xi_reco_24_toppt_a_up;       TH1F *DeltaY_xi_reco_24_toppt_a_down;
  TH1F *DeltaY_xi_reco_24_toppt_b_up;       TH1F *DeltaY_xi_reco_24_toppt_b_down;

  // lepton/trigger/pileup/prefiring - 30 bins
  TH1F *DeltaY_xi_reco_30_ele_reco_up;      TH1F *DeltaY_xi_reco_30_ele_reco_down;
  TH1F *DeltaY_xi_reco_30_ele_id_up;        TH1F *DeltaY_xi_reco_30_ele_id_down;
  TH1F *DeltaY_xi_reco_30_ele_trigger_up;   TH1F *DeltaY_xi_reco_30_ele_trigger_down;
  TH1F *DeltaY_xi_reco_30_mu_reco_up;       TH1F *DeltaY_xi_reco_30_mu_reco_down;
  TH1F *DeltaY_xi_reco_30_mu_iso_stat_up;   TH1F *DeltaY_xi_reco_30_mu_iso_stat_down;
  TH1F *DeltaY_xi_reco_30_mu_iso_syst_up;   TH1F *DeltaY_xi_reco_30_mu_iso_syst_down;
  TH1F *DeltaY_xi_reco_30_mu_id_stat_up;    TH1F *DeltaY_xi_reco_30_mu_id_stat_down;
  TH1F *DeltaY_xi_reco_30_mu_id_syst_up;    TH1F *DeltaY_xi_reco_30_mu_id_syst_down;
  TH1F *DeltaY_xi_reco_30_mu_trigger_stat_up; TH1F *DeltaY_xi_reco_30_mu_trigger_stat_down;
  TH1F *DeltaY_xi_reco_30_mu_trigger_syst_up; TH1F *DeltaY_xi_reco_30_mu_trigger_syst_down;
  TH1F *DeltaY_xi_reco_30_pu_up;            TH1F *DeltaY_xi_reco_30_pu_down;
  TH1F *DeltaY_xi_reco_30_prefiring_up;     TH1F *DeltaY_xi_reco_30_prefiring_down;
  // scales, isr fsr - 30 bins
  TH1F *DeltaY_xi_reco_30_murmuf_upup;      TH1F *DeltaY_xi_reco_30_murmuf_upnone;
  TH1F *DeltaY_xi_reco_30_murmuf_noneup;    TH1F *DeltaY_xi_reco_30_murmuf_nonedown;
  TH1F *DeltaY_xi_reco_30_murmuf_downnone;  TH1F *DeltaY_xi_reco_30_murmuf_downdown;
  TH1F *DeltaY_xi_reco_30_isr_up;           TH1F *DeltaY_xi_reco_30_isr_down;
  TH1F *DeltaY_xi_reco_30_fsr_up;           TH1F *DeltaY_xi_reco_30_fsr_down;
  // btag - 30 bins
  TH1F *DeltaY_xi_reco_30_btag_cferr1_up;   TH1F *DeltaY_xi_reco_30_btag_cferr1_down;
  TH1F *DeltaY_xi_reco_30_btag_cferr2_up;   TH1F *DeltaY_xi_reco_30_btag_cferr2_down;
  TH1F *DeltaY_xi_reco_30_btag_hf_up;       TH1F *DeltaY_xi_reco_30_btag_hf_down;
  TH1F *DeltaY_xi_reco_30_btag_hfstats1_up; TH1F *DeltaY_xi_reco_30_btag_hfstats1_down;
  TH1F *DeltaY_xi_reco_30_btag_hfstats2_up; TH1F *DeltaY_xi_reco_30_btag_hfstats2_down;
  TH1F *DeltaY_xi_reco_30_btag_lf_up;       TH1F *DeltaY_xi_reco_30_btag_lf_down;
  TH1F *DeltaY_xi_reco_30_btag_lfstats1_up; TH1F *DeltaY_xi_reco_30_btag_lfstats1_down;
  TH1F *DeltaY_xi_reco_30_btag_lfstats2_up; TH1F *DeltaY_xi_reco_30_btag_lfstats2_down;
  // ttag, mistag, toppt - 30 bins
  TH1F *DeltaY_xi_reco_30_ttag_corr_up;     TH1F *DeltaY_xi_reco_30_ttag_corr_down;
  TH1F *DeltaY_xi_reco_30_ttag_uncorr_up;   TH1F *DeltaY_xi_reco_30_ttag_uncorr_down;
  TH1F *DeltaY_xi_reco_30_tmistag_up;       TH1F *DeltaY_xi_reco_30_tmistag_down;
  TH1F *DeltaY_xi_reco_30_toppt_a_up;       TH1F *DeltaY_xi_reco_30_toppt_a_down;
  TH1F *DeltaY_xi_reco_30_toppt_b_up;       TH1F *DeltaY_xi_reco_30_toppt_b_down;


  TH1F *DeltaY_reco_d1_mu_reco_up;
  TH1F *DeltaY_reco_d1_mu_reco_down;
  TH1F *DeltaY_reco_d1_pu_up;
  TH1F *DeltaY_reco_d1_pu_down;
  TH1F *DeltaY_reco_d1_prefiring_up;
  TH1F *DeltaY_reco_d1_prefiring_down;
  TH1F *DeltaY_reco_d1_mu_iso_stat_up;
  TH1F *DeltaY_reco_d1_mu_iso_stat_down;
  TH1F *DeltaY_reco_d1_mu_iso_syst_up;
  TH1F *DeltaY_reco_d1_mu_iso_syst_down;
  TH1F *DeltaY_reco_d1_mu_id_stat_up;
  TH1F *DeltaY_reco_d1_mu_id_stat_down;
  TH1F *DeltaY_reco_d1_mu_id_syst_up;
  TH1F *DeltaY_reco_d1_mu_id_syst_down;
  TH1F *DeltaY_reco_d1_mu_trigger_stat_up;
  TH1F *DeltaY_reco_d1_mu_trigger_stat_down;
  TH1F *DeltaY_reco_d1_mu_trigger_syst_up;
  TH1F *DeltaY_reco_d1_mu_trigger_syst_down;
  TH1F *DeltaY_reco_d1_ele_id_up;
  TH1F *DeltaY_reco_d1_ele_id_down;
  TH1F *DeltaY_reco_d1_ele_trigger_up;
  TH1F *DeltaY_reco_d1_ele_trigger_down;
  TH1F *DeltaY_reco_d1_ele_reco_up;
  TH1F *DeltaY_reco_d1_ele_reco_down;
  TH1F *DeltaY_reco_d1_murmuf_upup;
  TH1F *DeltaY_reco_d1_murmuf_upnone;
  TH1F *DeltaY_reco_d1_murmuf_noneup;
  TH1F *DeltaY_reco_d1_murmuf_nonedown;
  TH1F *DeltaY_reco_d1_murmuf_downnone;
  TH1F *DeltaY_reco_d1_murmuf_downdown;
  TH1F *DeltaY_reco_d1_isr_up;
  TH1F *DeltaY_reco_d1_isr_down;
  TH1F *DeltaY_reco_d1_fsr_up;
  TH1F *DeltaY_reco_d1_fsr_down;
  TH1F *DeltaY_reco_d1_btag_cferr1_up;
  TH1F *DeltaY_reco_d1_btag_cferr1_down;
  TH1F *DeltaY_reco_d1_btag_cferr2_up;
  TH1F *DeltaY_reco_d1_btag_cferr2_down;
  TH1F *DeltaY_reco_d1_btag_hf_up;
  TH1F *DeltaY_reco_d1_btag_hf_down;
  TH1F *DeltaY_reco_d1_btag_hfstats1_up;
  TH1F *DeltaY_reco_d1_btag_hfstats1_down;
  TH1F *DeltaY_reco_d1_btag_hfstats2_up;
  TH1F *DeltaY_reco_d1_btag_hfstats2_down;
  TH1F *DeltaY_reco_d1_btag_lf_up;
  TH1F *DeltaY_reco_d1_btag_lf_down;
  TH1F *DeltaY_reco_d1_btag_lfstats1_up;
  TH1F *DeltaY_reco_d1_btag_lfstats1_down;
  TH1F *DeltaY_reco_d1_btag_lfstats2_up;
  TH1F *DeltaY_reco_d1_btag_lfstats2_down;
  TH1F *DeltaY_reco_d1_ttag_corr_up;
  TH1F *DeltaY_reco_d1_ttag_corr_down;
  TH1F *DeltaY_reco_d1_ttag_uncorr_up;
  TH1F *DeltaY_reco_d1_ttag_uncorr_down;
  TH1F *DeltaY_reco_d1_tmistag_up;
  TH1F *DeltaY_reco_d1_tmistag_down;
  TH1F *DeltaY_reco_d1_toppt_a_up;
  TH1F *DeltaY_reco_d1_toppt_a_down;
  TH1F *DeltaY_reco_d1_toppt_b_up;
  TH1F *DeltaY_reco_d1_toppt_b_down;


  TH1F *DeltaY_reco_d2_mu_reco_up;
  TH1F *DeltaY_reco_d2_mu_reco_down;
  TH1F *DeltaY_reco_d2_pu_up;
  TH1F *DeltaY_reco_d2_pu_down;
  TH1F *DeltaY_reco_d2_prefiring_up;
  TH1F *DeltaY_reco_d2_prefiring_down;
  TH1F *DeltaY_reco_d2_mu_iso_stat_up;
  TH1F *DeltaY_reco_d2_mu_iso_stat_down;
  TH1F *DeltaY_reco_d2_mu_iso_syst_up;
  TH1F *DeltaY_reco_d2_mu_iso_syst_down;
  TH1F *DeltaY_reco_d2_mu_id_stat_up;
  TH1F *DeltaY_reco_d2_mu_id_stat_down;
  TH1F *DeltaY_reco_d2_mu_id_syst_up;
  TH1F *DeltaY_reco_d2_mu_id_syst_down;
  TH1F *DeltaY_reco_d2_mu_trigger_stat_up;
  TH1F *DeltaY_reco_d2_mu_trigger_stat_down;
  TH1F *DeltaY_reco_d2_mu_trigger_syst_up;
  TH1F *DeltaY_reco_d2_mu_trigger_syst_down;
  TH1F *DeltaY_reco_d2_ele_id_up;
  TH1F *DeltaY_reco_d2_ele_id_down;
  TH1F *DeltaY_reco_d2_ele_trigger_up;
  TH1F *DeltaY_reco_d2_ele_trigger_down;
  TH1F *DeltaY_reco_d2_ele_reco_up;
  TH1F *DeltaY_reco_d2_ele_reco_down;
  TH1F *DeltaY_reco_d2_murmuf_upup;
  TH1F *DeltaY_reco_d2_murmuf_upnone;
  TH1F *DeltaY_reco_d2_murmuf_noneup;
  TH1F *DeltaY_reco_d2_murmuf_nonedown;
  TH1F *DeltaY_reco_d2_murmuf_downnone;
  TH1F *DeltaY_reco_d2_murmuf_downdown;
  TH1F *DeltaY_reco_d2_isr_up;
  TH1F *DeltaY_reco_d2_isr_down;
  TH1F *DeltaY_reco_d2_fsr_up;
  TH1F *DeltaY_reco_d2_fsr_down;
  TH1F *DeltaY_reco_d2_btag_cferr1_up;
  TH1F *DeltaY_reco_d2_btag_cferr1_down;
  TH1F *DeltaY_reco_d2_btag_cferr2_up;
  TH1F *DeltaY_reco_d2_btag_cferr2_down;
  TH1F *DeltaY_reco_d2_btag_hf_up;
  TH1F *DeltaY_reco_d2_btag_hf_down;
  TH1F *DeltaY_reco_d2_btag_hfstats1_up;
  TH1F *DeltaY_reco_d2_btag_hfstats1_down;
  TH1F *DeltaY_reco_d2_btag_hfstats2_up;
  TH1F *DeltaY_reco_d2_btag_hfstats2_down;
  TH1F *DeltaY_reco_d2_btag_lf_up;
  TH1F *DeltaY_reco_d2_btag_lf_down;
  TH1F *DeltaY_reco_d2_btag_lfstats1_up;
  TH1F *DeltaY_reco_d2_btag_lfstats1_down;
  TH1F *DeltaY_reco_d2_btag_lfstats2_up;
  TH1F *DeltaY_reco_d2_btag_lfstats2_down;
  TH1F *DeltaY_reco_d2_ttag_corr_up;
  TH1F *DeltaY_reco_d2_ttag_corr_down;
  TH1F *DeltaY_reco_d2_ttag_uncorr_up;
  TH1F *DeltaY_reco_d2_ttag_uncorr_down;
  TH1F *DeltaY_reco_d2_tmistag_up;
  TH1F *DeltaY_reco_d2_tmistag_down;
  TH1F *DeltaY_reco_d2_toppt_a_up;
  TH1F *DeltaY_reco_d2_toppt_a_down;
  TH1F *DeltaY_reco_d2_toppt_b_up;
  TH1F *DeltaY_reco_d2_toppt_b_down;


  TH1F *Sigma_phi_1_mu_reco_up;
  TH1F *Sigma_phi_1_mu_reco_down;
  TH1F *Sigma_phi_1_pu_up;
  TH1F *Sigma_phi_1_pu_down;
  TH1F *Sigma_phi_1_prefiring_up;
  TH1F *Sigma_phi_1_prefiring_down;
  TH1F *Sigma_phi_1_mu_iso_stat_up;
  TH1F *Sigma_phi_1_mu_iso_stat_down;
  TH1F *Sigma_phi_1_mu_iso_syst_up;
  TH1F *Sigma_phi_1_mu_iso_syst_down;
  TH1F *Sigma_phi_1_mu_id_stat_up;
  TH1F *Sigma_phi_1_mu_id_stat_down;
  TH1F *Sigma_phi_1_mu_id_syst_up;
  TH1F *Sigma_phi_1_mu_id_syst_down;
  TH1F *Sigma_phi_1_mu_trigger_stat_up;
  TH1F *Sigma_phi_1_mu_trigger_stat_down;
  TH1F *Sigma_phi_1_mu_trigger_syst_up;
  TH1F *Sigma_phi_1_mu_trigger_syst_down;
  TH1F *Sigma_phi_1_ele_id_up;
  TH1F *Sigma_phi_1_ele_id_down;
  TH1F *Sigma_phi_1_ele_trigger_up;
  TH1F *Sigma_phi_1_ele_trigger_down;
  TH1F *Sigma_phi_1_ele_reco_up;
  TH1F *Sigma_phi_1_ele_reco_down;
  TH1F *Sigma_phi_1_murmuf_upup;
  TH1F *Sigma_phi_1_murmuf_upnone;
  TH1F *Sigma_phi_1_murmuf_noneup;
  TH1F *Sigma_phi_1_murmuf_nonedown;
  TH1F *Sigma_phi_1_murmuf_downnone;
  TH1F *Sigma_phi_1_murmuf_downdown;
  TH1F *Sigma_phi_1_isr_up;
  TH1F *Sigma_phi_1_isr_down;
  TH1F *Sigma_phi_1_fsr_up;
  TH1F *Sigma_phi_1_fsr_down;
  TH1F *Sigma_phi_1_btag_cferr1_up;
  TH1F *Sigma_phi_1_btag_cferr1_down;
  TH1F *Sigma_phi_1_btag_cferr2_up;
  TH1F *Sigma_phi_1_btag_cferr2_down;
  TH1F *Sigma_phi_1_btag_hf_up;
  TH1F *Sigma_phi_1_btag_hf_down;
  TH1F *Sigma_phi_1_btag_hfstats1_up;
  TH1F *Sigma_phi_1_btag_hfstats1_down;
  TH1F *Sigma_phi_1_btag_hfstats2_up;
  TH1F *Sigma_phi_1_btag_hfstats2_down;
  TH1F *Sigma_phi_1_btag_lf_up;
  TH1F *Sigma_phi_1_btag_lf_down;
  TH1F *Sigma_phi_1_btag_lfstats1_up;
  TH1F *Sigma_phi_1_btag_lfstats1_down;
  TH1F *Sigma_phi_1_btag_lfstats2_up;
  TH1F *Sigma_phi_1_btag_lfstats2_down;
  TH1F *Sigma_phi_1_ttag_corr_up;
  TH1F *Sigma_phi_1_ttag_corr_down;
  TH1F *Sigma_phi_1_ttag_uncorr_up;
  TH1F *Sigma_phi_1_ttag_uncorr_down;
  TH1F *Sigma_phi_1_tmistag_up;
  TH1F *Sigma_phi_1_tmistag_down;
  TH1F *Sigma_phi_1_toppt_a_up;
  TH1F *Sigma_phi_1_toppt_a_down;
  TH1F *Sigma_phi_1_toppt_b_up;
  TH1F *Sigma_phi_1_toppt_b_down;

  // electron systematics
  TH1F *Sigma_phi_2_ele_reco_up;
  TH1F *Sigma_phi_2_ele_reco_down;
  TH1F *Sigma_phi_2_ele_id_up;
  TH1F *Sigma_phi_2_ele_id_down;
  TH1F *Sigma_phi_2_ele_trigger_up;
  TH1F *Sigma_phi_2_ele_trigger_down;
  // muon systematics
  TH1F *Sigma_phi_2_mu_reco_up;
  TH1F *Sigma_phi_2_mu_reco_down;
  TH1F *Sigma_phi_2_mu_id_stat_up;
  TH1F *Sigma_phi_2_mu_id_stat_down;
  TH1F *Sigma_phi_2_mu_id_syst_up;
  TH1F *Sigma_phi_2_mu_id_syst_down;
  TH1F *Sigma_phi_2_mu_trigger_stat_up;
  TH1F *Sigma_phi_2_mu_trigger_stat_down;
  TH1F *Sigma_phi_2_mu_trigger_syst_up;
  TH1F *Sigma_phi_2_mu_trigger_syst_down;
  TH1F *Sigma_phi_2_mu_iso_stat_up;
  TH1F *Sigma_phi_2_mu_iso_stat_down;
  TH1F *Sigma_phi_2_mu_iso_syst_up;
  TH1F *Sigma_phi_2_mu_iso_syst_down;
  // Pileup reweighting systematics
  TH1F *Sigma_phi_2_pu_up;
  TH1F *Sigma_phi_2_pu_down;
  // Prefiring systematics
  TH1F *Sigma_phi_2_prefiring_up;
  TH1F *Sigma_phi_2_prefiring_down;
  // b-tagging systematics
  TH1F *Sigma_phi_2_btag_cferr1_up;
  TH1F *Sigma_phi_2_btag_cferr1_down;
  TH1F *Sigma_phi_2_btag_cferr2_up;
  TH1F *Sigma_phi_2_btag_cferr2_down;
  TH1F *Sigma_phi_2_btag_hf_up;
  TH1F *Sigma_phi_2_btag_hf_down;
  TH1F *Sigma_phi_2_btag_hfstats1_up;
  TH1F *Sigma_phi_2_btag_hfstats1_down;
  TH1F *Sigma_phi_2_btag_hfstats2_up;
  TH1F *Sigma_phi_2_btag_hfstats2_down;
  TH1F *Sigma_phi_2_btag_lf_up;
  TH1F *Sigma_phi_2_btag_lf_down;
  TH1F *Sigma_phi_2_btag_lfstats1_up;
  TH1F *Sigma_phi_2_btag_lfstats1_down;
  TH1F *Sigma_phi_2_btag_lfstats2_up;
  TH1F *Sigma_phi_2_btag_lfstats2_down;
  // Top tagging systematics
  TH1F *Sigma_phi_2_ttag_corr_up;
  TH1F *Sigma_phi_2_ttag_corr_down;
  TH1F *Sigma_phi_2_ttag_uncorr_up;
  TH1F *Sigma_phi_2_ttag_uncorr_down;
  // Top mistagging systematics
  TH1F *Sigma_phi_2_tmistag_up;
  TH1F *Sigma_phi_2_tmistag_down;
  // Top pT reweighting systematics
  TH1F *Sigma_phi_2_toppt_a_up;
  TH1F *Sigma_phi_2_toppt_a_down;
  TH1F *Sigma_phi_2_toppt_b_up;
  TH1F *Sigma_phi_2_toppt_b_down;
  // muR and muF at ME level systematics
  TH1F *Sigma_phi_2_murmuf_upup;
  TH1F *Sigma_phi_2_murmuf_upnone;
  TH1F *Sigma_phi_2_murmuf_noneup;
  TH1F *Sigma_phi_2_murmuf_nonedown;
  TH1F *Sigma_phi_2_murmuf_downnone;
  TH1F *Sigma_phi_2_murmuf_downdown;
  // ISR and FSR systematics
  TH1F *Sigma_phi_2_isr_up;
  TH1F *Sigma_phi_2_isr_down;
  TH1F *Sigma_phi_2_fsr_up;
  TH1F *Sigma_phi_2_fsr_down;

  // // cos_theta1k_antiLep
  // // electron systematics
  // TH1F *cos_theta1k_antiLep_ele_reco_up;
  // TH1F *cos_theta1k_antiLep_ele_reco_down;
  // TH1F *cos_theta1k_antiLep_ele_id_up;
  // TH1F *cos_theta1k_antiLep_ele_id_down;
  // TH1F *cos_theta1k_antiLep_ele_trigger_up;
  // TH1F *cos_theta1k_antiLep_ele_trigger_down;
  // // muon systematics
  // TH1F *cos_theta1k_antiLep_mu_reco_up;
  // TH1F *cos_theta1k_antiLep_mu_reco_down;
  // TH1F *cos_theta1k_antiLep_mu_id_stat_up;
  // TH1F *cos_theta1k_antiLep_mu_id_stat_down;
  // TH1F *cos_theta1k_antiLep_mu_id_syst_up;
  // TH1F *cos_theta1k_antiLep_mu_id_syst_down;
  // TH1F *cos_theta1k_antiLep_mu_trigger_stat_up;
  // TH1F *cos_theta1k_antiLep_mu_trigger_stat_down;
  // TH1F *cos_theta1k_antiLep_mu_trigger_syst_up;
  // TH1F *cos_theta1k_antiLep_mu_trigger_syst_down;
  // TH1F *cos_theta1k_antiLep_mu_iso_stat_up;
  // TH1F *cos_theta1k_antiLep_mu_iso_stat_down;
  // TH1F *cos_theta1k_antiLep_mu_iso_syst_up;
  // TH1F *cos_theta1k_antiLep_mu_iso_syst_down;
  // // Pileup reweighting systematics
  // TH1F *cos_theta1k_antiLep_pu_up;
  // TH1F *cos_theta1k_antiLep_pu_down;
  // // Prefiring systematics
  // TH1F *cos_theta1k_antiLep_prefiring_up;
  // TH1F *cos_theta1k_antiLep_prefiring_down;
  // // b-tagging systematics
  // TH1F *cos_theta1k_antiLep_btag_cferr1_up;
  // TH1F *cos_theta1k_antiLep_btag_cferr1_down;
  // TH1F *cos_theta1k_antiLep_btag_cferr2_up;
  // TH1F *cos_theta1k_antiLep_btag_cferr2_down;
  // TH1F *cos_theta1k_antiLep_btag_hf_up;
  // TH1F *cos_theta1k_antiLep_btag_hf_down;
  // TH1F *cos_theta1k_antiLep_btag_hfstats1_up;
  // TH1F *cos_theta1k_antiLep_btag_hfstats1_down;
  // TH1F *cos_theta1k_antiLep_btag_hfstats2_up;
  // TH1F *cos_theta1k_antiLep_btag_hfstats2_down;
  // TH1F *cos_theta1k_antiLep_btag_lf_up;
  // TH1F *cos_theta1k_antiLep_btag_lf_down;
  // TH1F *cos_theta1k_antiLep_btag_lfstats1_up;
  // TH1F *cos_theta1k_antiLep_btag_lfstats1_down;
  // TH1F *cos_theta1k_antiLep_btag_lfstats2_up;
  // TH1F *cos_theta1k_antiLep_btag_lfstats2_down;
  // // Top tagging systematics
  // TH1F *cos_theta1k_antiLep_ttag_corr_up;
  // TH1F *cos_theta1k_antiLep_ttag_corr_down;
  // TH1F *cos_theta1k_antiLep_ttag_uncorr_up;
  // TH1F *cos_theta1k_antiLep_ttag_uncorr_down;
  // // Top mistagging systematics
  // TH1F *cos_theta1k_antiLep_tmistag_up;
  // TH1F *cos_theta1k_antiLep_tmistag_down;
  // // Top pT reweighting systematics
  // TH1F *cos_theta1k_antiLep_toppt_a_up;
  // TH1F *cos_theta1k_antiLep_toppt_a_down;
  // TH1F *cos_theta1k_antiLep_toppt_b_up;
  // TH1F *cos_theta1k_antiLep_toppt_b_down;
  // // muR and muF at ME level systematics
  // TH1F *cos_theta1k_antiLep_murmuf_upup;
  // TH1F *cos_theta1k_antiLep_murmuf_upnone;
  // TH1F *cos_theta1k_antiLep_murmuf_noneup;
  // TH1F *cos_theta1k_antiLep_murmuf_nonedown;
  // TH1F *cos_theta1k_antiLep_murmuf_downnone;
  // TH1F *cos_theta1k_antiLep_murmuf_downdown;
  // // ISR and FSR systematics
  // TH1F *cos_theta1k_antiLep_isr_up;
  // TH1F *cos_theta1k_antiLep_isr_down;
  // TH1F *cos_theta1k_antiLep_fsr_up;
  // TH1F *cos_theta1k_antiLep_fsr_down;

  // // cos_theta1r_antiLep
  // TH1F *cos_theta1r_antiLep_ele_reco_up;
  // TH1F *cos_theta1r_antiLep_ele_reco_down;
  // TH1F *cos_theta1r_antiLep_ele_id_up;
  // TH1F *cos_theta1r_antiLep_ele_id_down;
  // TH1F *cos_theta1r_antiLep_ele_trigger_up;
  // TH1F *cos_theta1r_antiLep_ele_trigger_down;
  // TH1F *cos_theta1r_antiLep_mu_reco_up;
  // TH1F *cos_theta1r_antiLep_mu_reco_down;
  // TH1F *cos_theta1r_antiLep_mu_id_stat_up;
  // TH1F *cos_theta1r_antiLep_mu_id_stat_down;
  // TH1F *cos_theta1r_antiLep_mu_id_syst_up;
  // TH1F *cos_theta1r_antiLep_mu_id_syst_down;
  // TH1F *cos_theta1r_antiLep_mu_trigger_stat_up;
  // TH1F *cos_theta1r_antiLep_mu_trigger_stat_down;
  // TH1F *cos_theta1r_antiLep_mu_trigger_syst_up;
  // TH1F *cos_theta1r_antiLep_mu_trigger_syst_down;
  // TH1F *cos_theta1r_antiLep_mu_iso_stat_up;
  // TH1F *cos_theta1r_antiLep_mu_iso_stat_down;
  // TH1F *cos_theta1r_antiLep_mu_iso_syst_up;
  // TH1F *cos_theta1r_antiLep_mu_iso_syst_down;
  // TH1F *cos_theta1r_antiLep_pu_up;
  // TH1F *cos_theta1r_antiLep_pu_down;
  // TH1F *cos_theta1r_antiLep_prefiring_up;
  // TH1F *cos_theta1r_antiLep_prefiring_down;
  // TH1F *cos_theta1r_antiLep_btag_cferr1_up;
  // TH1F *cos_theta1r_antiLep_btag_cferr1_down;
  // TH1F *cos_theta1r_antiLep_btag_cferr2_up;
  // TH1F *cos_theta1r_antiLep_btag_cferr2_down;
  // TH1F *cos_theta1r_antiLep_btag_hf_up;
  // TH1F *cos_theta1r_antiLep_btag_hf_down;
  // TH1F *cos_theta1r_antiLep_btag_hfstats1_up;
  // TH1F *cos_theta1r_antiLep_btag_hfstats1_down;
  // TH1F *cos_theta1r_antiLep_btag_hfstats2_up;
  // TH1F *cos_theta1r_antiLep_btag_hfstats2_down;
  // TH1F *cos_theta1r_antiLep_btag_lf_up;
  // TH1F *cos_theta1r_antiLep_btag_lf_down;
  // TH1F *cos_theta1r_antiLep_btag_lfstats1_up;
  // TH1F *cos_theta1r_antiLep_btag_lfstats1_down;
  // TH1F *cos_theta1r_antiLep_btag_lfstats2_up;
  // TH1F *cos_theta1r_antiLep_btag_lfstats2_down;
  // TH1F *cos_theta1r_antiLep_ttag_corr_up;
  // TH1F *cos_theta1r_antiLep_ttag_corr_down;
  // TH1F *cos_theta1r_antiLep_ttag_uncorr_up;
  // TH1F *cos_theta1r_antiLep_ttag_uncorr_down;
  // TH1F *cos_theta1r_antiLep_tmistag_up;
  // TH1F *cos_theta1r_antiLep_tmistag_down;
  // TH1F *cos_theta1r_antiLep_toppt_a_up;
  // TH1F *cos_theta1r_antiLep_toppt_a_down;
  // TH1F *cos_theta1r_antiLep_toppt_b_up;
  // TH1F *cos_theta1r_antiLep_toppt_b_down;
  // TH1F *cos_theta1r_antiLep_murmuf_upup;
  // TH1F *cos_theta1r_antiLep_murmuf_upnone;
  // TH1F *cos_theta1r_antiLep_murmuf_noneup;
  // TH1F *cos_theta1r_antiLep_murmuf_nonedown;
  // TH1F *cos_theta1r_antiLep_murmuf_downnone;
  // TH1F *cos_theta1r_antiLep_murmuf_downdown;
  // TH1F *cos_theta1r_antiLep_isr_up;
  // TH1F *cos_theta1r_antiLep_isr_down;
  // TH1F *cos_theta1r_antiLep_fsr_up;
  // TH1F *cos_theta1r_antiLep_fsr_down;

  // // cos_theta1n_antiLep
  // TH1F *cos_theta1n_antiLep_ele_reco_up;
  // TH1F *cos_theta1n_antiLep_ele_reco_down;
  // TH1F *cos_theta1n_antiLep_ele_id_up;
  // TH1F *cos_theta1n_antiLep_ele_id_down;
  // TH1F *cos_theta1n_antiLep_ele_trigger_up;
  // TH1F *cos_theta1n_antiLep_ele_trigger_down;
  // TH1F *cos_theta1n_antiLep_mu_reco_up;
  // TH1F *cos_theta1n_antiLep_mu_reco_down;
  // TH1F *cos_theta1n_antiLep_mu_id_stat_up;
  // TH1F *cos_theta1n_antiLep_mu_id_stat_down;
  // TH1F *cos_theta1n_antiLep_mu_id_syst_up;
  // TH1F *cos_theta1n_antiLep_mu_id_syst_down;
  // TH1F *cos_theta1n_antiLep_mu_trigger_stat_up;
  // TH1F *cos_theta1n_antiLep_mu_trigger_stat_down;
  // TH1F *cos_theta1n_antiLep_mu_trigger_syst_up;
  // TH1F *cos_theta1n_antiLep_mu_trigger_syst_down;
  // TH1F *cos_theta1n_antiLep_mu_iso_stat_up;
  // TH1F *cos_theta1n_antiLep_mu_iso_stat_down;
  // TH1F *cos_theta1n_antiLep_mu_iso_syst_up;
  // TH1F *cos_theta1n_antiLep_mu_iso_syst_down;
  // TH1F *cos_theta1n_antiLep_pu_up;
  // TH1F *cos_theta1n_antiLep_pu_down;
  // TH1F *cos_theta1n_antiLep_prefiring_up;
  // TH1F *cos_theta1n_antiLep_prefiring_down;
  // TH1F *cos_theta1n_antiLep_btag_cferr1_up;
  // TH1F *cos_theta1n_antiLep_btag_cferr1_down;
  // TH1F *cos_theta1n_antiLep_btag_cferr2_up;
  // TH1F *cos_theta1n_antiLep_btag_cferr2_down;
  // TH1F *cos_theta1n_antiLep_btag_hf_up;
  // TH1F *cos_theta1n_antiLep_btag_hf_down;
  // TH1F *cos_theta1n_antiLep_btag_hfstats1_up;
  // TH1F *cos_theta1n_antiLep_btag_hfstats1_down;
  // TH1F *cos_theta1n_antiLep_btag_hfstats2_up;
  // TH1F *cos_theta1n_antiLep_btag_hfstats2_down;
  // TH1F *cos_theta1n_antiLep_btag_lf_up;
  // TH1F *cos_theta1n_antiLep_btag_lf_down;
  // TH1F *cos_theta1n_antiLep_btag_lfstats1_up;
  // TH1F *cos_theta1n_antiLep_btag_lfstats1_down;
  // TH1F *cos_theta1n_antiLep_btag_lfstats2_up;
  // TH1F *cos_theta1n_antiLep_btag_lfstats2_down;
  // TH1F *cos_theta1n_antiLep_ttag_corr_up;
  // TH1F *cos_theta1n_antiLep_ttag_corr_down;
  // TH1F *cos_theta1n_antiLep_ttag_uncorr_up;
  // TH1F *cos_theta1n_antiLep_ttag_uncorr_down;
  // TH1F *cos_theta1n_antiLep_tmistag_up;
  // TH1F *cos_theta1n_antiLep_tmistag_down;
  // TH1F *cos_theta1n_antiLep_toppt_a_up;
  // TH1F *cos_theta1n_antiLep_toppt_a_down;
  // TH1F *cos_theta1n_antiLep_toppt_b_up;
  // TH1F *cos_theta1n_antiLep_toppt_b_down;
  // TH1F *cos_theta1n_antiLep_murmuf_upup;
  // TH1F *cos_theta1n_antiLep_murmuf_upnone;
  // TH1F *cos_theta1n_antiLep_murmuf_noneup;
  // TH1F *cos_theta1n_antiLep_murmuf_nonedown;
  // TH1F *cos_theta1n_antiLep_murmuf_downnone;
  // TH1F *cos_theta1n_antiLep_murmuf_downdown;
  // TH1F *cos_theta1n_antiLep_isr_up;
  // TH1F *cos_theta1n_antiLep_isr_down;
  // TH1F *cos_theta1n_antiLep_fsr_up;
  // TH1F *cos_theta1n_antiLep_fsr_down;

  // // cos_theta1kStar_antiLep
  // TH1F *cos_theta1kStar_antiLep_ele_reco_up;
  // TH1F *cos_theta1kStar_antiLep_ele_reco_down;
  // TH1F *cos_theta1kStar_antiLep_ele_id_up;
  // TH1F *cos_theta1kStar_antiLep_ele_id_down;
  // TH1F *cos_theta1kStar_antiLep_ele_trigger_up;
  // TH1F *cos_theta1kStar_antiLep_ele_trigger_down;
  // TH1F *cos_theta1kStar_antiLep_mu_reco_up;
  // TH1F *cos_theta1kStar_antiLep_mu_reco_down;
  // TH1F *cos_theta1kStar_antiLep_mu_id_stat_up;
  // TH1F *cos_theta1kStar_antiLep_mu_id_stat_down;
  // TH1F *cos_theta1kStar_antiLep_mu_id_syst_up;
  // TH1F *cos_theta1kStar_antiLep_mu_id_syst_down;
  // TH1F *cos_theta1kStar_antiLep_mu_trigger_stat_up;
  // TH1F *cos_theta1kStar_antiLep_mu_trigger_stat_down;
  // TH1F *cos_theta1kStar_antiLep_mu_trigger_syst_up;
  // TH1F *cos_theta1kStar_antiLep_mu_trigger_syst_down;
  // TH1F *cos_theta1kStar_antiLep_mu_iso_stat_up;
  // TH1F *cos_theta1kStar_antiLep_mu_iso_stat_down;
  // TH1F *cos_theta1kStar_antiLep_mu_iso_syst_up;
  // TH1F *cos_theta1kStar_antiLep_mu_iso_syst_down;
  // TH1F *cos_theta1kStar_antiLep_pu_up;
  // TH1F *cos_theta1kStar_antiLep_pu_down;
  // TH1F *cos_theta1kStar_antiLep_prefiring_up;
  // TH1F *cos_theta1kStar_antiLep_prefiring_down;
  // TH1F *cos_theta1kStar_antiLep_btag_cferr1_up;
  // TH1F *cos_theta1kStar_antiLep_btag_cferr1_down;
  // TH1F *cos_theta1kStar_antiLep_btag_cferr2_up;
  // TH1F *cos_theta1kStar_antiLep_btag_cferr2_down;
  // TH1F *cos_theta1kStar_antiLep_btag_hf_up;
  // TH1F *cos_theta1kStar_antiLep_btag_hf_down;
  // TH1F *cos_theta1kStar_antiLep_btag_hfstats1_up;
  // TH1F *cos_theta1kStar_antiLep_btag_hfstats1_down;
  // TH1F *cos_theta1kStar_antiLep_btag_hfstats2_up;
  // TH1F *cos_theta1kStar_antiLep_btag_hfstats2_down;
  // TH1F *cos_theta1kStar_antiLep_btag_lf_up;
  // TH1F *cos_theta1kStar_antiLep_btag_lf_down;
  // TH1F *cos_theta1kStar_antiLep_btag_lfstats1_up;
  // TH1F *cos_theta1kStar_antiLep_btag_lfstats1_down;
  // TH1F *cos_theta1kStar_antiLep_btag_lfstats2_up;
  // TH1F *cos_theta1kStar_antiLep_btag_lfstats2_down;
  // TH1F *cos_theta1kStar_antiLep_ttag_corr_up;
  // TH1F *cos_theta1kStar_antiLep_ttag_corr_down;
  // TH1F *cos_theta1kStar_antiLep_ttag_uncorr_up;
  // TH1F *cos_theta1kStar_antiLep_ttag_uncorr_down;
  // TH1F *cos_theta1kStar_antiLep_tmistag_up;
  // TH1F *cos_theta1kStar_antiLep_tmistag_down;
  // TH1F *cos_theta1kStar_antiLep_toppt_a_up;
  // TH1F *cos_theta1kStar_antiLep_toppt_a_down;
  // TH1F *cos_theta1kStar_antiLep_toppt_b_up;
  // TH1F *cos_theta1kStar_antiLep_toppt_b_down;
  // TH1F *cos_theta1kStar_antiLep_murmuf_upup;
  // TH1F *cos_theta1kStar_antiLep_murmuf_upnone;
  // TH1F *cos_theta1kStar_antiLep_murmuf_noneup;
  // TH1F *cos_theta1kStar_antiLep_murmuf_nonedown;
  // TH1F *cos_theta1kStar_antiLep_murmuf_downnone;
  // TH1F *cos_theta1kStar_antiLep_murmuf_downdown;
  // TH1F *cos_theta1kStar_antiLep_isr_up;
  // TH1F *cos_theta1kStar_antiLep_isr_down;
  // TH1F *cos_theta1kStar_antiLep_fsr_up;
  // TH1F *cos_theta1kStar_antiLep_fsr_down;

  // // cos_theta1rStar_antiLep
  // TH1F *cos_theta1rStar_antiLep_ele_reco_up;
  // TH1F *cos_theta1rStar_antiLep_ele_reco_down;
  // TH1F *cos_theta1rStar_antiLep_ele_id_up;
  // TH1F *cos_theta1rStar_antiLep_ele_id_down;
  // TH1F *cos_theta1rStar_antiLep_ele_trigger_up;
  // TH1F *cos_theta1rStar_antiLep_ele_trigger_down;
  // TH1F *cos_theta1rStar_antiLep_mu_reco_up;
  // TH1F *cos_theta1rStar_antiLep_mu_reco_down;
  // TH1F *cos_theta1rStar_antiLep_mu_id_stat_up;
  // TH1F *cos_theta1rStar_antiLep_mu_id_stat_down;
  // TH1F *cos_theta1rStar_antiLep_mu_id_syst_up;
  // TH1F *cos_theta1rStar_antiLep_mu_id_syst_down;
  // TH1F *cos_theta1rStar_antiLep_mu_trigger_stat_up;
  // TH1F *cos_theta1rStar_antiLep_mu_trigger_stat_down;
  // TH1F *cos_theta1rStar_antiLep_mu_trigger_syst_up;
  // TH1F *cos_theta1rStar_antiLep_mu_trigger_syst_down;
  // TH1F *cos_theta1rStar_antiLep_mu_iso_stat_up;
  // TH1F *cos_theta1rStar_antiLep_mu_iso_stat_down;
  // TH1F *cos_theta1rStar_antiLep_mu_iso_syst_up;
  // TH1F *cos_theta1rStar_antiLep_mu_iso_syst_down;
  // TH1F *cos_theta1rStar_antiLep_pu_up;
  // TH1F *cos_theta1rStar_antiLep_pu_down;
  // TH1F *cos_theta1rStar_antiLep_prefiring_up;
  // TH1F *cos_theta1rStar_antiLep_prefiring_down;
  // TH1F *cos_theta1rStar_antiLep_btag_cferr1_up;
  // TH1F *cos_theta1rStar_antiLep_btag_cferr1_down;
  // TH1F *cos_theta1rStar_antiLep_btag_cferr2_up;
  // TH1F *cos_theta1rStar_antiLep_btag_cferr2_down;
  // TH1F *cos_theta1rStar_antiLep_btag_hf_up;
  // TH1F *cos_theta1rStar_antiLep_btag_hf_down;
  // TH1F *cos_theta1rStar_antiLep_btag_hfstats1_up;
  // TH1F *cos_theta1rStar_antiLep_btag_hfstats1_down;
  // TH1F *cos_theta1rStar_antiLep_btag_hfstats2_up;
  // TH1F *cos_theta1rStar_antiLep_btag_hfstats2_down;
  // TH1F *cos_theta1rStar_antiLep_btag_lf_up;
  // TH1F *cos_theta1rStar_antiLep_btag_lf_down;
  // TH1F *cos_theta1rStar_antiLep_btag_lfstats1_up;
  // TH1F *cos_theta1rStar_antiLep_btag_lfstats1_down;
  // TH1F *cos_theta1rStar_antiLep_btag_lfstats2_up;
  // TH1F *cos_theta1rStar_antiLep_btag_lfstats2_down;
  // TH1F *cos_theta1rStar_antiLep_ttag_corr_up;
  // TH1F *cos_theta1rStar_antiLep_ttag_corr_down;
  // TH1F *cos_theta1rStar_antiLep_ttag_uncorr_up;
  // TH1F *cos_theta1rStar_antiLep_ttag_uncorr_down;
  // TH1F *cos_theta1rStar_antiLep_tmistag_up;
  // TH1F *cos_theta1rStar_antiLep_tmistag_down;
  // TH1F *cos_theta1rStar_antiLep_toppt_a_up;
  // TH1F *cos_theta1rStar_antiLep_toppt_a_down;
  // TH1F *cos_theta1rStar_antiLep_toppt_b_up;
  // TH1F *cos_theta1rStar_antiLep_toppt_b_down;
  // TH1F *cos_theta1rStar_antiLep_murmuf_upup;
  // TH1F *cos_theta1rStar_antiLep_murmuf_upnone;
  // TH1F *cos_theta1rStar_antiLep_murmuf_noneup;
  // TH1F *cos_theta1rStar_antiLep_murmuf_nonedown;
  // TH1F *cos_theta1rStar_antiLep_murmuf_downnone;
  // TH1F *cos_theta1rStar_antiLep_murmuf_downdown;
  // TH1F *cos_theta1rStar_antiLep_isr_up;
  // TH1F *cos_theta1rStar_antiLep_isr_down;
  // TH1F *cos_theta1rStar_antiLep_fsr_up;
  // TH1F *cos_theta1rStar_antiLep_fsr_down;

  // // cos_theta2k_Lep
  // TH1F *cos_theta2k_Lep_ele_reco_up;
  // TH1F *cos_theta2k_Lep_ele_reco_down;
  // TH1F *cos_theta2k_Lep_ele_id_up;
  // TH1F *cos_theta2k_Lep_ele_id_down;
  // TH1F *cos_theta2k_Lep_ele_trigger_up;
  // TH1F *cos_theta2k_Lep_ele_trigger_down;
  // TH1F *cos_theta2k_Lep_mu_reco_up;
  // TH1F *cos_theta2k_Lep_mu_reco_down;
  // TH1F *cos_theta2k_Lep_mu_id_stat_up;
  // TH1F *cos_theta2k_Lep_mu_id_stat_down;
  // TH1F *cos_theta2k_Lep_mu_id_syst_up;
  // TH1F *cos_theta2k_Lep_mu_id_syst_down;
  // TH1F *cos_theta2k_Lep_mu_trigger_stat_up;
  // TH1F *cos_theta2k_Lep_mu_trigger_stat_down;
  // TH1F *cos_theta2k_Lep_mu_trigger_syst_up;
  // TH1F *cos_theta2k_Lep_mu_trigger_syst_down;
  // TH1F *cos_theta2k_Lep_mu_iso_stat_up;
  // TH1F *cos_theta2k_Lep_mu_iso_stat_down;
  // TH1F *cos_theta2k_Lep_mu_iso_syst_up;
  // TH1F *cos_theta2k_Lep_mu_iso_syst_down;
  // TH1F *cos_theta2k_Lep_pu_up;
  // TH1F *cos_theta2k_Lep_pu_down;
  // TH1F *cos_theta2k_Lep_prefiring_up;
  // TH1F *cos_theta2k_Lep_prefiring_down;
  // TH1F *cos_theta2k_Lep_btag_cferr1_up;
  // TH1F *cos_theta2k_Lep_btag_cferr1_down;
  // TH1F *cos_theta2k_Lep_btag_cferr2_up;
  // TH1F *cos_theta2k_Lep_btag_cferr2_down;
  // TH1F *cos_theta2k_Lep_btag_hf_up;
  // TH1F *cos_theta2k_Lep_btag_hf_down;
  // TH1F *cos_theta2k_Lep_btag_hfstats1_up;
  // TH1F *cos_theta2k_Lep_btag_hfstats1_down;
  // TH1F *cos_theta2k_Lep_btag_hfstats2_up;
  // TH1F *cos_theta2k_Lep_btag_hfstats2_down;
  // TH1F *cos_theta2k_Lep_btag_lf_up;
  // TH1F *cos_theta2k_Lep_btag_lf_down;
  // TH1F *cos_theta2k_Lep_btag_lfstats1_up;
  // TH1F *cos_theta2k_Lep_btag_lfstats1_down;
  // TH1F *cos_theta2k_Lep_btag_lfstats2_up;
  // TH1F *cos_theta2k_Lep_btag_lfstats2_down;
  // TH1F *cos_theta2k_Lep_ttag_corr_up;
  // TH1F *cos_theta2k_Lep_ttag_corr_down;
  // TH1F *cos_theta2k_Lep_ttag_uncorr_up;
  // TH1F *cos_theta2k_Lep_ttag_uncorr_down;
  // TH1F *cos_theta2k_Lep_tmistag_up;
  // TH1F *cos_theta2k_Lep_tmistag_down;
  // TH1F *cos_theta2k_Lep_toppt_a_up;
  // TH1F *cos_theta2k_Lep_toppt_a_down;
  // TH1F *cos_theta2k_Lep_toppt_b_up;
  // TH1F *cos_theta2k_Lep_toppt_b_down;
  // TH1F *cos_theta2k_Lep_murmuf_upup;
  // TH1F *cos_theta2k_Lep_murmuf_upnone;
  // TH1F *cos_theta2k_Lep_murmuf_noneup;
  // TH1F *cos_theta2k_Lep_murmuf_nonedown;
  // TH1F *cos_theta2k_Lep_murmuf_downnone;
  // TH1F *cos_theta2k_Lep_murmuf_downdown;
  // TH1F *cos_theta2k_Lep_isr_up;
  // TH1F *cos_theta2k_Lep_isr_down;
  // TH1F *cos_theta2k_Lep_fsr_up;
  // TH1F *cos_theta2k_Lep_fsr_down;

  // // cos_theta2r_Lep
  // TH1F *cos_theta2r_Lep_ele_reco_up;
  // TH1F *cos_theta2r_Lep_ele_reco_down;
  // TH1F *cos_theta2r_Lep_ele_id_up;
  // TH1F *cos_theta2r_Lep_ele_id_down;
  // TH1F *cos_theta2r_Lep_ele_trigger_up;
  // TH1F *cos_theta2r_Lep_ele_trigger_down;
  // TH1F *cos_theta2r_Lep_mu_reco_up;
  // TH1F *cos_theta2r_Lep_mu_reco_down;
  // TH1F *cos_theta2r_Lep_mu_id_stat_up;
  // TH1F *cos_theta2r_Lep_mu_id_stat_down;
  // TH1F *cos_theta2r_Lep_mu_id_syst_up;
  // TH1F *cos_theta2r_Lep_mu_id_syst_down;
  // TH1F *cos_theta2r_Lep_mu_trigger_stat_up;
  // TH1F *cos_theta2r_Lep_mu_trigger_stat_down;
  // TH1F *cos_theta2r_Lep_mu_trigger_syst_up;
  // TH1F *cos_theta2r_Lep_mu_trigger_syst_down;
  // TH1F *cos_theta2r_Lep_mu_iso_stat_up;
  // TH1F *cos_theta2r_Lep_mu_iso_stat_down;
  // TH1F *cos_theta2r_Lep_mu_iso_syst_up;
  // TH1F *cos_theta2r_Lep_mu_iso_syst_down;
  // TH1F *cos_theta2r_Lep_pu_up;
  // TH1F *cos_theta2r_Lep_pu_down;
  // TH1F *cos_theta2r_Lep_prefiring_up;
  // TH1F *cos_theta2r_Lep_prefiring_down;
  // TH1F *cos_theta2r_Lep_btag_cferr1_up;
  // TH1F *cos_theta2r_Lep_btag_cferr1_down;
  // TH1F *cos_theta2r_Lep_btag_cferr2_up;
  // TH1F *cos_theta2r_Lep_btag_cferr2_down;
  // TH1F *cos_theta2r_Lep_btag_hf_up;
  // TH1F *cos_theta2r_Lep_btag_hf_down;
  // TH1F *cos_theta2r_Lep_btag_hfstats1_up;
  // TH1F *cos_theta2r_Lep_btag_hfstats1_down;
  // TH1F *cos_theta2r_Lep_btag_hfstats2_up;
  // TH1F *cos_theta2r_Lep_btag_hfstats2_down;
  // TH1F *cos_theta2r_Lep_btag_lf_up;
  // TH1F *cos_theta2r_Lep_btag_lf_down;
  // TH1F *cos_theta2r_Lep_btag_lfstats1_up;
  // TH1F *cos_theta2r_Lep_btag_lfstats1_down;
  // TH1F *cos_theta2r_Lep_btag_lfstats2_up;
  // TH1F *cos_theta2r_Lep_btag_lfstats2_down;
  // TH1F *cos_theta2r_Lep_ttag_corr_up;
  // TH1F *cos_theta2r_Lep_ttag_corr_down;
  // TH1F *cos_theta2r_Lep_ttag_uncorr_up;
  // TH1F *cos_theta2r_Lep_ttag_uncorr_down;
  // TH1F *cos_theta2r_Lep_tmistag_up;
  // TH1F *cos_theta2r_Lep_tmistag_down;
  // TH1F *cos_theta2r_Lep_toppt_a_up;
  // TH1F *cos_theta2r_Lep_toppt_a_down;
  // TH1F *cos_theta2r_Lep_toppt_b_up;
  // TH1F *cos_theta2r_Lep_toppt_b_down;
  // TH1F *cos_theta2r_Lep_murmuf_upup;
  // TH1F *cos_theta2r_Lep_murmuf_upnone;
  // TH1F *cos_theta2r_Lep_murmuf_noneup;
  // TH1F *cos_theta2r_Lep_murmuf_nonedown;
  // TH1F *cos_theta2r_Lep_murmuf_downnone;
  // TH1F *cos_theta2r_Lep_murmuf_downdown;
  // TH1F *cos_theta2r_Lep_isr_up;
  // TH1F *cos_theta2r_Lep_isr_down;
  // TH1F *cos_theta2r_Lep_fsr_up;
  // TH1F *cos_theta2r_Lep_fsr_down;

  // // cos_theta2n_Lep
  // TH1F *cos_theta2n_Lep_ele_reco_up;
  // TH1F *cos_theta2n_Lep_ele_reco_down;
  // TH1F *cos_theta2n_Lep_ele_id_up;
  // TH1F *cos_theta2n_Lep_ele_id_down;
  // TH1F *cos_theta2n_Lep_ele_trigger_up;
  // TH1F *cos_theta2n_Lep_ele_trigger_down;
  // TH1F *cos_theta2n_Lep_mu_reco_up;
  // TH1F *cos_theta2n_Lep_mu_reco_down;
  // TH1F *cos_theta2n_Lep_mu_id_stat_up;
  // TH1F *cos_theta2n_Lep_mu_id_stat_down;
  // TH1F *cos_theta2n_Lep_mu_id_syst_up;
  // TH1F *cos_theta2n_Lep_mu_id_syst_down;
  // TH1F *cos_theta2n_Lep_mu_trigger_stat_up;
  // TH1F *cos_theta2n_Lep_mu_trigger_stat_down;
  // TH1F *cos_theta2n_Lep_mu_trigger_syst_up;
  // TH1F *cos_theta2n_Lep_mu_trigger_syst_down;
  // TH1F *cos_theta2n_Lep_mu_iso_stat_up;
  // TH1F *cos_theta2n_Lep_mu_iso_stat_down;
  // TH1F *cos_theta2n_Lep_mu_iso_syst_up;
  // TH1F *cos_theta2n_Lep_mu_iso_syst_down;
  // TH1F *cos_theta2n_Lep_pu_up;
  // TH1F *cos_theta2n_Lep_pu_down;
  // TH1F *cos_theta2n_Lep_prefiring_up;
  // TH1F *cos_theta2n_Lep_prefiring_down;
  // TH1F *cos_theta2n_Lep_btag_cferr1_up;
  // TH1F *cos_theta2n_Lep_btag_cferr1_down;
  // TH1F *cos_theta2n_Lep_btag_cferr2_up;
  // TH1F *cos_theta2n_Lep_btag_cferr2_down;
  // TH1F *cos_theta2n_Lep_btag_hf_up;
  // TH1F *cos_theta2n_Lep_btag_hf_down;
  // TH1F *cos_theta2n_Lep_btag_hfstats1_up;
  // TH1F *cos_theta2n_Lep_btag_hfstats1_down;
  // TH1F *cos_theta2n_Lep_btag_hfstats2_up;
  // TH1F *cos_theta2n_Lep_btag_hfstats2_down;
  // TH1F *cos_theta2n_Lep_btag_lf_up;
  // TH1F *cos_theta2n_Lep_btag_lf_down;
  // TH1F *cos_theta2n_Lep_btag_lfstats1_up;
  // TH1F *cos_theta2n_Lep_btag_lfstats1_down;
  // TH1F *cos_theta2n_Lep_btag_lfstats2_up;
  // TH1F *cos_theta2n_Lep_btag_lfstats2_down;
  // TH1F *cos_theta2n_Lep_ttag_corr_up;
  // TH1F *cos_theta2n_Lep_ttag_corr_down;
  // TH1F *cos_theta2n_Lep_ttag_uncorr_up;
  // TH1F *cos_theta2n_Lep_ttag_uncorr_down;
  // TH1F *cos_theta2n_Lep_tmistag_up;
  // TH1F *cos_theta2n_Lep_tmistag_down;
  // TH1F *cos_theta2n_Lep_toppt_a_up;
  // TH1F *cos_theta2n_Lep_toppt_a_down;
  // TH1F *cos_theta2n_Lep_toppt_b_up;
  // TH1F *cos_theta2n_Lep_toppt_b_down;
  // TH1F *cos_theta2n_Lep_murmuf_upup;
  // TH1F *cos_theta2n_Lep_murmuf_upnone;
  // TH1F *cos_theta2n_Lep_murmuf_noneup;
  // TH1F *cos_theta2n_Lep_murmuf_nonedown;
  // TH1F *cos_theta2n_Lep_murmuf_downnone;
  // TH1F *cos_theta2n_Lep_murmuf_downdown;
  // TH1F *cos_theta2n_Lep_isr_up;
  // TH1F *cos_theta2n_Lep_isr_down;
  // TH1F *cos_theta2n_Lep_fsr_up;
  // TH1F *cos_theta2n_Lep_fsr_down;

  // // cos_theta2kStar_Lep
  // TH1F *cos_theta2kStar_Lep_ele_reco_up;
  // TH1F *cos_theta2kStar_Lep_ele_reco_down;
  // TH1F *cos_theta2kStar_Lep_ele_id_up;
  // TH1F *cos_theta2kStar_Lep_ele_id_down;
  // TH1F *cos_theta2kStar_Lep_ele_trigger_up;
  // TH1F *cos_theta2kStar_Lep_ele_trigger_down;
  // TH1F *cos_theta2kStar_Lep_mu_reco_up;
  // TH1F *cos_theta2kStar_Lep_mu_reco_down;
  // TH1F *cos_theta2kStar_Lep_mu_id_stat_up;
  // TH1F *cos_theta2kStar_Lep_mu_id_stat_down;
  // TH1F *cos_theta2kStar_Lep_mu_id_syst_up;
  // TH1F *cos_theta2kStar_Lep_mu_id_syst_down;
  // TH1F *cos_theta2kStar_Lep_mu_trigger_stat_up;
  // TH1F *cos_theta2kStar_Lep_mu_trigger_stat_down;
  // TH1F *cos_theta2kStar_Lep_mu_trigger_syst_up;
  // TH1F *cos_theta2kStar_Lep_mu_trigger_syst_down;
  // TH1F *cos_theta2kStar_Lep_mu_iso_stat_up;
  // TH1F *cos_theta2kStar_Lep_mu_iso_stat_down;
  // TH1F *cos_theta2kStar_Lep_mu_iso_syst_up;
  // TH1F *cos_theta2kStar_Lep_mu_iso_syst_down;
  // TH1F *cos_theta2kStar_Lep_pu_up;
  // TH1F *cos_theta2kStar_Lep_pu_down;
  // TH1F *cos_theta2kStar_Lep_prefiring_up;
  // TH1F *cos_theta2kStar_Lep_prefiring_down;
  // TH1F *cos_theta2kStar_Lep_btag_cferr1_up;
  // TH1F *cos_theta2kStar_Lep_btag_cferr1_down;
  // TH1F *cos_theta2kStar_Lep_btag_cferr2_up;
  // TH1F *cos_theta2kStar_Lep_btag_cferr2_down;
  // TH1F *cos_theta2kStar_Lep_btag_hf_up;
  // TH1F *cos_theta2kStar_Lep_btag_hf_down;
  // TH1F *cos_theta2kStar_Lep_btag_hfstats1_up;
  // TH1F *cos_theta2kStar_Lep_btag_hfstats1_down;
  // TH1F *cos_theta2kStar_Lep_btag_hfstats2_up;
  // TH1F *cos_theta2kStar_Lep_btag_hfstats2_down;
  // TH1F *cos_theta2kStar_Lep_btag_lf_up;
  // TH1F *cos_theta2kStar_Lep_btag_lf_down;
  // TH1F *cos_theta2kStar_Lep_btag_lfstats1_up;
  // TH1F *cos_theta2kStar_Lep_btag_lfstats1_down;
  // TH1F *cos_theta2kStar_Lep_btag_lfstats2_up;
  // TH1F *cos_theta2kStar_Lep_btag_lfstats2_down;
  // TH1F *cos_theta2kStar_Lep_ttag_corr_up;
  // TH1F *cos_theta2kStar_Lep_ttag_corr_down;
  // TH1F *cos_theta2kStar_Lep_ttag_uncorr_up;
  // TH1F *cos_theta2kStar_Lep_ttag_uncorr_down;
  // TH1F *cos_theta2kStar_Lep_tmistag_up;
  // TH1F *cos_theta2kStar_Lep_tmistag_down;
  // TH1F *cos_theta2kStar_Lep_toppt_a_up;
  // TH1F *cos_theta2kStar_Lep_toppt_a_down;
  // TH1F *cos_theta2kStar_Lep_toppt_b_up;
  // TH1F *cos_theta2kStar_Lep_toppt_b_down;
  // TH1F *cos_theta2kStar_Lep_murmuf_upup;
  // TH1F *cos_theta2kStar_Lep_murmuf_upnone;
  // TH1F *cos_theta2kStar_Lep_murmuf_noneup;
  // TH1F *cos_theta2kStar_Lep_murmuf_nonedown;
  // TH1F *cos_theta2kStar_Lep_murmuf_downnone;
  // TH1F *cos_theta2kStar_Lep_murmuf_downdown;
  // TH1F *cos_theta2kStar_Lep_isr_up;
  // TH1F *cos_theta2kStar_Lep_isr_down;
  // TH1F *cos_theta2kStar_Lep_fsr_up;
  // TH1F *cos_theta2kStar_Lep_fsr_down;

  // // cos_theta2rStar_Lep
  // TH1F *cos_theta2rStar_Lep_ele_reco_up;
  // TH1F *cos_theta2rStar_Lep_ele_reco_down;
  // TH1F *cos_theta2rStar_Lep_ele_id_up;
  // TH1F *cos_theta2rStar_Lep_ele_id_down;
  // TH1F *cos_theta2rStar_Lep_ele_trigger_up;
  // TH1F *cos_theta2rStar_Lep_ele_trigger_down;
  // TH1F *cos_theta2rStar_Lep_mu_reco_up;
  // TH1F *cos_theta2rStar_Lep_mu_reco_down;
  // TH1F *cos_theta2rStar_Lep_mu_id_stat_up;
  // TH1F *cos_theta2rStar_Lep_mu_id_stat_down;
  // TH1F *cos_theta2rStar_Lep_mu_id_syst_up;
  // TH1F *cos_theta2rStar_Lep_mu_id_syst_down;
  // TH1F *cos_theta2rStar_Lep_mu_trigger_stat_up;
  // TH1F *cos_theta2rStar_Lep_mu_trigger_stat_down;
  // TH1F *cos_theta2rStar_Lep_mu_trigger_syst_up;
  // TH1F *cos_theta2rStar_Lep_mu_trigger_syst_down;
  // TH1F *cos_theta2rStar_Lep_mu_iso_stat_up;
  // TH1F *cos_theta2rStar_Lep_mu_iso_stat_down;
  // TH1F *cos_theta2rStar_Lep_mu_iso_syst_up;
  // TH1F *cos_theta2rStar_Lep_mu_iso_syst_down;
  // TH1F *cos_theta2rStar_Lep_pu_up;
  // TH1F *cos_theta2rStar_Lep_pu_down;
  // TH1F *cos_theta2rStar_Lep_prefiring_up;
  // TH1F *cos_theta2rStar_Lep_prefiring_down;
  // TH1F *cos_theta2rStar_Lep_btag_cferr1_up;
  // TH1F *cos_theta2rStar_Lep_btag_cferr1_down;
  // TH1F *cos_theta2rStar_Lep_btag_cferr2_up;
  // TH1F *cos_theta2rStar_Lep_btag_cferr2_down;
  // TH1F *cos_theta2rStar_Lep_btag_hf_up;
  // TH1F *cos_theta2rStar_Lep_btag_hf_down;
  // TH1F *cos_theta2rStar_Lep_btag_hfstats1_up;
  // TH1F *cos_theta2rStar_Lep_btag_hfstats1_down;
  // TH1F *cos_theta2rStar_Lep_btag_hfstats2_up;
  // TH1F *cos_theta2rStar_Lep_btag_hfstats2_down;
  // TH1F *cos_theta2rStar_Lep_btag_lf_up;
  // TH1F *cos_theta2rStar_Lep_btag_lf_down;
  // TH1F *cos_theta2rStar_Lep_btag_lfstats1_up;
  // TH1F *cos_theta2rStar_Lep_btag_lfstats1_down;
  // TH1F *cos_theta2rStar_Lep_btag_lfstats2_up;
  // TH1F *cos_theta2rStar_Lep_btag_lfstats2_down;
  // TH1F *cos_theta2rStar_Lep_ttag_corr_up;
  // TH1F *cos_theta2rStar_Lep_ttag_corr_down;
  // TH1F *cos_theta2rStar_Lep_ttag_uncorr_up;
  // TH1F *cos_theta2rStar_Lep_ttag_uncorr_down;
  // TH1F *cos_theta2rStar_Lep_tmistag_up;
  // TH1F *cos_theta2rStar_Lep_tmistag_down;
  // TH1F *cos_theta2rStar_Lep_toppt_a_up;
  // TH1F *cos_theta2rStar_Lep_toppt_a_down;
  // TH1F *cos_theta2rStar_Lep_toppt_b_up;
  // TH1F *cos_theta2rStar_Lep_toppt_b_down;
  // TH1F *cos_theta2rStar_Lep_murmuf_upup;
  // TH1F *cos_theta2rStar_Lep_murmuf_upnone;
  // TH1F *cos_theta2rStar_Lep_murmuf_noneup;
  // TH1F *cos_theta2rStar_Lep_murmuf_nonedown;
  // TH1F *cos_theta2rStar_Lep_murmuf_downnone;
  // TH1F *cos_theta2rStar_Lep_murmuf_downdown;
  // TH1F *cos_theta2rStar_Lep_isr_up;
  // TH1F *cos_theta2rStar_Lep_isr_down;
  // TH1F *cos_theta2rStar_Lep_fsr_up;
  // TH1F *cos_theta2rStar_Lep_fsr_down;

  // cos_theta1k
  TH1F *cos_theta1k_ele_reco_up;
  TH1F *cos_theta1k_ele_reco_down;
  TH1F *cos_theta1k_ele_id_up;
  TH1F *cos_theta1k_ele_id_down;
  TH1F *cos_theta1k_ele_trigger_up;
  TH1F *cos_theta1k_ele_trigger_down;
  TH1F *cos_theta1k_mu_reco_up;
  TH1F *cos_theta1k_mu_reco_down;
  TH1F *cos_theta1k_mu_id_stat_up;
  TH1F *cos_theta1k_mu_id_stat_down;
  TH1F *cos_theta1k_mu_id_syst_up;
  TH1F *cos_theta1k_mu_id_syst_down;
  TH1F *cos_theta1k_mu_trigger_stat_up;
  TH1F *cos_theta1k_mu_trigger_stat_down;
  TH1F *cos_theta1k_mu_trigger_syst_up;
  TH1F *cos_theta1k_mu_trigger_syst_down;
  TH1F *cos_theta1k_mu_iso_stat_up;
  TH1F *cos_theta1k_mu_iso_stat_down;
  TH1F *cos_theta1k_mu_iso_syst_up;
  TH1F *cos_theta1k_mu_iso_syst_down;
  TH1F *cos_theta1k_pu_up;
  TH1F *cos_theta1k_pu_down;
  TH1F *cos_theta1k_prefiring_up;
  TH1F *cos_theta1k_prefiring_down;
  TH1F *cos_theta1k_btag_cferr1_up;
  TH1F *cos_theta1k_btag_cferr1_down;
  TH1F *cos_theta1k_btag_cferr2_up;
  TH1F *cos_theta1k_btag_cferr2_down;
  TH1F *cos_theta1k_btag_hf_up;
  TH1F *cos_theta1k_btag_hf_down;
  TH1F *cos_theta1k_btag_hfstats1_up;
  TH1F *cos_theta1k_btag_hfstats1_down;
  TH1F *cos_theta1k_btag_hfstats2_up;
  TH1F *cos_theta1k_btag_hfstats2_down;
  TH1F *cos_theta1k_btag_lf_up;
  TH1F *cos_theta1k_btag_lf_down;
  TH1F *cos_theta1k_btag_lfstats1_up;
  TH1F *cos_theta1k_btag_lfstats1_down;
  TH1F *cos_theta1k_btag_lfstats2_up;
  TH1F *cos_theta1k_btag_lfstats2_down;
  TH1F *cos_theta1k_ttag_corr_up;
  TH1F *cos_theta1k_ttag_corr_down;
  TH1F *cos_theta1k_ttag_uncorr_up;
  TH1F *cos_theta1k_ttag_uncorr_down;
  TH1F *cos_theta1k_tmistag_up;
  TH1F *cos_theta1k_tmistag_down;
  TH1F *cos_theta1k_toppt_a_up;
  TH1F *cos_theta1k_toppt_a_down;
  TH1F *cos_theta1k_toppt_b_up;
  TH1F *cos_theta1k_toppt_b_down;
  TH1F *cos_theta1k_murmuf_upup;
  TH1F *cos_theta1k_murmuf_upnone;
  TH1F *cos_theta1k_murmuf_noneup;
  TH1F *cos_theta1k_murmuf_nonedown;
  TH1F *cos_theta1k_murmuf_downnone;
  TH1F *cos_theta1k_murmuf_downdown;
  TH1F *cos_theta1k_isr_up;
  TH1F *cos_theta1k_isr_down;
  TH1F *cos_theta1k_fsr_up;
  TH1F *cos_theta1k_fsr_down;

  // cos_theta1r
  TH1F *cos_theta1r_ele_reco_up;
  TH1F *cos_theta1r_ele_reco_down;
  TH1F *cos_theta1r_ele_id_up;
  TH1F *cos_theta1r_ele_id_down;
  TH1F *cos_theta1r_ele_trigger_up;
  TH1F *cos_theta1r_ele_trigger_down;
  TH1F *cos_theta1r_mu_reco_up;
  TH1F *cos_theta1r_mu_reco_down;
  TH1F *cos_theta1r_mu_id_stat_up;
  TH1F *cos_theta1r_mu_id_stat_down;
  TH1F *cos_theta1r_mu_id_syst_up;
  TH1F *cos_theta1r_mu_id_syst_down;
  TH1F *cos_theta1r_mu_trigger_stat_up;
  TH1F *cos_theta1r_mu_trigger_stat_down;
  TH1F *cos_theta1r_mu_trigger_syst_up;
  TH1F *cos_theta1r_mu_trigger_syst_down;
  TH1F *cos_theta1r_mu_iso_stat_up;
  TH1F *cos_theta1r_mu_iso_stat_down;
  TH1F *cos_theta1r_mu_iso_syst_up;
  TH1F *cos_theta1r_mu_iso_syst_down;
  TH1F *cos_theta1r_pu_up;
  TH1F *cos_theta1r_pu_down;
  TH1F *cos_theta1r_prefiring_up;
  TH1F *cos_theta1r_prefiring_down;
  TH1F *cos_theta1r_btag_cferr1_up;
  TH1F *cos_theta1r_btag_cferr1_down;
  TH1F *cos_theta1r_btag_cferr2_up;
  TH1F *cos_theta1r_btag_cferr2_down;
  TH1F *cos_theta1r_btag_hf_up;
  TH1F *cos_theta1r_btag_hf_down;
  TH1F *cos_theta1r_btag_hfstats1_up;
  TH1F *cos_theta1r_btag_hfstats1_down;
  TH1F *cos_theta1r_btag_hfstats2_up;
  TH1F *cos_theta1r_btag_hfstats2_down;
  TH1F *cos_theta1r_btag_lf_up;
  TH1F *cos_theta1r_btag_lf_down;
  TH1F *cos_theta1r_btag_lfstats1_up;
  TH1F *cos_theta1r_btag_lfstats1_down;
  TH1F *cos_theta1r_btag_lfstats2_up;
  TH1F *cos_theta1r_btag_lfstats2_down;
  TH1F *cos_theta1r_ttag_corr_up;
  TH1F *cos_theta1r_ttag_corr_down;
  TH1F *cos_theta1r_ttag_uncorr_up;
  TH1F *cos_theta1r_ttag_uncorr_down;
  TH1F *cos_theta1r_tmistag_up;
  TH1F *cos_theta1r_tmistag_down;
  TH1F *cos_theta1r_toppt_a_up;
  TH1F *cos_theta1r_toppt_a_down;
  TH1F *cos_theta1r_toppt_b_up;
  TH1F *cos_theta1r_toppt_b_down;
  TH1F *cos_theta1r_murmuf_upup;
  TH1F *cos_theta1r_murmuf_upnone;
  TH1F *cos_theta1r_murmuf_noneup;
  TH1F *cos_theta1r_murmuf_nonedown;
  TH1F *cos_theta1r_murmuf_downnone;
  TH1F *cos_theta1r_murmuf_downdown;
  TH1F *cos_theta1r_isr_up;
  TH1F *cos_theta1r_isr_down;
  TH1F *cos_theta1r_fsr_up;
  TH1F *cos_theta1r_fsr_down;

  // cos_theta1n
  TH1F *cos_theta1n_ele_reco_up;
  TH1F *cos_theta1n_ele_reco_down;
  TH1F *cos_theta1n_ele_id_up;
  TH1F *cos_theta1n_ele_id_down;
  TH1F *cos_theta1n_ele_trigger_up;
  TH1F *cos_theta1n_ele_trigger_down;
  TH1F *cos_theta1n_mu_reco_up;
  TH1F *cos_theta1n_mu_reco_down;
  TH1F *cos_theta1n_mu_id_stat_up;
  TH1F *cos_theta1n_mu_id_stat_down;
  TH1F *cos_theta1n_mu_id_syst_up;
  TH1F *cos_theta1n_mu_id_syst_down;
  TH1F *cos_theta1n_mu_trigger_stat_up;
  TH1F *cos_theta1n_mu_trigger_stat_down;
  TH1F *cos_theta1n_mu_trigger_syst_up;
  TH1F *cos_theta1n_mu_trigger_syst_down;
  TH1F *cos_theta1n_mu_iso_stat_up;
  TH1F *cos_theta1n_mu_iso_stat_down;
  TH1F *cos_theta1n_mu_iso_syst_up;
  TH1F *cos_theta1n_mu_iso_syst_down;
  TH1F *cos_theta1n_pu_up;
  TH1F *cos_theta1n_pu_down;
  TH1F *cos_theta1n_prefiring_up;
  TH1F *cos_theta1n_prefiring_down;
  TH1F *cos_theta1n_btag_cferr1_up;
  TH1F *cos_theta1n_btag_cferr1_down;
  TH1F *cos_theta1n_btag_cferr2_up;
  TH1F *cos_theta1n_btag_cferr2_down;
  TH1F *cos_theta1n_btag_hf_up;
  TH1F *cos_theta1n_btag_hf_down;
  TH1F *cos_theta1n_btag_hfstats1_up;
  TH1F *cos_theta1n_btag_hfstats1_down;
  TH1F *cos_theta1n_btag_hfstats2_up;
  TH1F *cos_theta1n_btag_hfstats2_down;
  TH1F *cos_theta1n_btag_lf_up;
  TH1F *cos_theta1n_btag_lf_down;
  TH1F *cos_theta1n_btag_lfstats1_up;
  TH1F *cos_theta1n_btag_lfstats1_down;
  TH1F *cos_theta1n_btag_lfstats2_up;
  TH1F *cos_theta1n_btag_lfstats2_down;
  TH1F *cos_theta1n_ttag_corr_up;
  TH1F *cos_theta1n_ttag_corr_down;
  TH1F *cos_theta1n_ttag_uncorr_up;
  TH1F *cos_theta1n_ttag_uncorr_down;
  TH1F *cos_theta1n_tmistag_up;
  TH1F *cos_theta1n_tmistag_down;
  TH1F *cos_theta1n_toppt_a_up;
  TH1F *cos_theta1n_toppt_a_down;
  TH1F *cos_theta1n_toppt_b_up;
  TH1F *cos_theta1n_toppt_b_down;
  TH1F *cos_theta1n_murmuf_upup;
  TH1F *cos_theta1n_murmuf_upnone;
  TH1F *cos_theta1n_murmuf_noneup;
  TH1F *cos_theta1n_murmuf_nonedown;
  TH1F *cos_theta1n_murmuf_downnone;
  TH1F *cos_theta1n_murmuf_downdown;
  TH1F *cos_theta1n_isr_up;
  TH1F *cos_theta1n_isr_down;
  TH1F *cos_theta1n_fsr_up;
  TH1F *cos_theta1n_fsr_down;

  // // cos_theta1kStar
  // TH1F *cos_theta1kStar_ele_reco_up;
  // TH1F *cos_theta1kStar_ele_reco_down;
  // TH1F *cos_theta1kStar_ele_id_up;
  // TH1F *cos_theta1kStar_ele_id_down;
  // TH1F *cos_theta1kStar_ele_trigger_up;
  // TH1F *cos_theta1kStar_ele_trigger_down;
  // TH1F *cos_theta1kStar_mu_reco_up;
  // TH1F *cos_theta1kStar_mu_reco_down;
  // TH1F *cos_theta1kStar_mu_id_stat_up;
  // TH1F *cos_theta1kStar_mu_id_stat_down;
  // TH1F *cos_theta1kStar_mu_id_syst_up;
  // TH1F *cos_theta1kStar_mu_id_syst_down;
  // TH1F *cos_theta1kStar_mu_trigger_stat_up;
  // TH1F *cos_theta1kStar_mu_trigger_stat_down;
  // TH1F *cos_theta1kStar_mu_trigger_syst_up;
  // TH1F *cos_theta1kStar_mu_trigger_syst_down;
  // TH1F *cos_theta1kStar_mu_iso_stat_up;
  // TH1F *cos_theta1kStar_mu_iso_stat_down;
  // TH1F *cos_theta1kStar_mu_iso_syst_up;
  // TH1F *cos_theta1kStar_mu_iso_syst_down;
  // TH1F *cos_theta1kStar_pu_up;
  // TH1F *cos_theta1kStar_pu_down;
  // TH1F *cos_theta1kStar_prefiring_up;
  // TH1F *cos_theta1kStar_prefiring_down;
  // TH1F *cos_theta1kStar_btag_cferr1_up;
  // TH1F *cos_theta1kStar_btag_cferr1_down;
  // TH1F *cos_theta1kStar_btag_cferr2_up;
  // TH1F *cos_theta1kStar_btag_cferr2_down;
  // TH1F *cos_theta1kStar_btag_hf_up;
  // TH1F *cos_theta1kStar_btag_hf_down;
  // TH1F *cos_theta1kStar_btag_hfstats1_up;
  // TH1F *cos_theta1kStar_btag_hfstats1_down;
  // TH1F *cos_theta1kStar_btag_hfstats2_up;
  // TH1F *cos_theta1kStar_btag_hfstats2_down;
  // TH1F *cos_theta1kStar_btag_lf_up;
  // TH1F *cos_theta1kStar_btag_lf_down;
  // TH1F *cos_theta1kStar_btag_lfstats1_up;
  // TH1F *cos_theta1kStar_btag_lfstats1_down;
  // TH1F *cos_theta1kStar_btag_lfstats2_up;
  // TH1F *cos_theta1kStar_btag_lfstats2_down;
  // TH1F *cos_theta1kStar_ttag_corr_up;
  // TH1F *cos_theta1kStar_ttag_corr_down;
  // TH1F *cos_theta1kStar_ttag_uncorr_up;
  // TH1F *cos_theta1kStar_ttag_uncorr_down;
  // TH1F *cos_theta1kStar_tmistag_up;
  // TH1F *cos_theta1kStar_tmistag_down;
  // TH1F *cos_theta1kStar_toppt_a_up;
  // TH1F *cos_theta1kStar_toppt_a_down;
  // TH1F *cos_theta1kStar_toppt_b_up;
  // TH1F *cos_theta1kStar_toppt_b_down;
  // TH1F *cos_theta1kStar_murmuf_upup;
  // TH1F *cos_theta1kStar_murmuf_upnone;
  // TH1F *cos_theta1kStar_murmuf_noneup;
  // TH1F *cos_theta1kStar_murmuf_nonedown;
  // TH1F *cos_theta1kStar_murmuf_downnone;
  // TH1F *cos_theta1kStar_murmuf_downdown;
  // TH1F *cos_theta1kStar_isr_up;
  // TH1F *cos_theta1kStar_isr_down;
  // TH1F *cos_theta1kStar_fsr_up;
  // TH1F *cos_theta1kStar_fsr_down;

  // // cos_theta1rStar
  // TH1F *cos_theta1rStar_ele_reco_up;
  // TH1F *cos_theta1rStar_ele_reco_down;
  // TH1F *cos_theta1rStar_ele_id_up;
  // TH1F *cos_theta1rStar_ele_id_down;
  // TH1F *cos_theta1rStar_ele_trigger_up;
  // TH1F *cos_theta1rStar_ele_trigger_down;
  // TH1F *cos_theta1rStar_mu_reco_up;
  // TH1F *cos_theta1rStar_mu_reco_down;
  // TH1F *cos_theta1rStar_mu_id_stat_up;
  // TH1F *cos_theta1rStar_mu_id_stat_down;
  // TH1F *cos_theta1rStar_mu_id_syst_up;
  // TH1F *cos_theta1rStar_mu_id_syst_down;
  // TH1F *cos_theta1rStar_mu_trigger_stat_up;
  // TH1F *cos_theta1rStar_mu_trigger_stat_down;
  // TH1F *cos_theta1rStar_mu_trigger_syst_up;
  // TH1F *cos_theta1rStar_mu_trigger_syst_down;
  // TH1F *cos_theta1rStar_mu_iso_stat_up;
  // TH1F *cos_theta1rStar_mu_iso_stat_down;
  // TH1F *cos_theta1rStar_mu_iso_syst_up;
  // TH1F *cos_theta1rStar_mu_iso_syst_down;
  // TH1F *cos_theta1rStar_pu_up;
  // TH1F *cos_theta1rStar_pu_down;
  // TH1F *cos_theta1rStar_prefiring_up;
  // TH1F *cos_theta1rStar_prefiring_down;
  // TH1F *cos_theta1rStar_btag_cferr1_up;
  // TH1F *cos_theta1rStar_btag_cferr1_down;
  // TH1F *cos_theta1rStar_btag_cferr2_up;
  // TH1F *cos_theta1rStar_btag_cferr2_down;
  // TH1F *cos_theta1rStar_btag_hf_up;
  // TH1F *cos_theta1rStar_btag_hf_down;
  // TH1F *cos_theta1rStar_btag_hfstats1_up;
  // TH1F *cos_theta1rStar_btag_hfstats1_down;
  // TH1F *cos_theta1rStar_btag_hfstats2_up;
  // TH1F *cos_theta1rStar_btag_hfstats2_down;
  // TH1F *cos_theta1rStar_btag_lf_up;
  // TH1F *cos_theta1rStar_btag_lf_down;
  // TH1F *cos_theta1rStar_btag_lfstats1_up;
  // TH1F *cos_theta1rStar_btag_lfstats1_down;
  // TH1F *cos_theta1rStar_btag_lfstats2_up;
  // TH1F *cos_theta1rStar_btag_lfstats2_down;
  // TH1F *cos_theta1rStar_ttag_corr_up;
  // TH1F *cos_theta1rStar_ttag_corr_down;
  // TH1F *cos_theta1rStar_ttag_uncorr_up;
  // TH1F *cos_theta1rStar_ttag_uncorr_down;
  // TH1F *cos_theta1rStar_tmistag_up;
  // TH1F *cos_theta1rStar_tmistag_down;
  // TH1F *cos_theta1rStar_toppt_a_up;
  // TH1F *cos_theta1rStar_toppt_a_down;
  // TH1F *cos_theta1rStar_toppt_b_up;
  // TH1F *cos_theta1rStar_toppt_b_down;
  // TH1F *cos_theta1rStar_murmuf_upup;
  // TH1F *cos_theta1rStar_murmuf_upnone;
  // TH1F *cos_theta1rStar_murmuf_noneup;
  // TH1F *cos_theta1rStar_murmuf_nonedown;
  // TH1F *cos_theta1rStar_murmuf_downnone;
  // TH1F *cos_theta1rStar_murmuf_downdown;
  // TH1F *cos_theta1rStar_isr_up;
  // TH1F *cos_theta1rStar_isr_down;
  // TH1F *cos_theta1rStar_fsr_up;
  // TH1F *cos_theta1rStar_fsr_down;

  // cos_theta2k
  TH1F *cos_theta2k_ele_reco_up;
  TH1F *cos_theta2k_ele_reco_down;
  TH1F *cos_theta2k_ele_id_up;
  TH1F *cos_theta2k_ele_id_down;
  TH1F *cos_theta2k_ele_trigger_up;
  TH1F *cos_theta2k_ele_trigger_down;
  TH1F *cos_theta2k_mu_reco_up;
  TH1F *cos_theta2k_mu_reco_down;
  TH1F *cos_theta2k_mu_id_stat_up;
  TH1F *cos_theta2k_mu_id_stat_down;
  TH1F *cos_theta2k_mu_id_syst_up;
  TH1F *cos_theta2k_mu_id_syst_down;
  TH1F *cos_theta2k_mu_trigger_stat_up;
  TH1F *cos_theta2k_mu_trigger_stat_down;
  TH1F *cos_theta2k_mu_trigger_syst_up;
  TH1F *cos_theta2k_mu_trigger_syst_down;
  TH1F *cos_theta2k_mu_iso_stat_up;
  TH1F *cos_theta2k_mu_iso_stat_down;
  TH1F *cos_theta2k_mu_iso_syst_up;
  TH1F *cos_theta2k_mu_iso_syst_down;
  TH1F *cos_theta2k_pu_up;
  TH1F *cos_theta2k_pu_down;
  TH1F *cos_theta2k_prefiring_up;
  TH1F *cos_theta2k_prefiring_down;
  TH1F *cos_theta2k_btag_cferr1_up;
  TH1F *cos_theta2k_btag_cferr1_down;
  TH1F *cos_theta2k_btag_cferr2_up;
  TH1F *cos_theta2k_btag_cferr2_down;
  TH1F *cos_theta2k_btag_hf_up;
  TH1F *cos_theta2k_btag_hf_down;
  TH1F *cos_theta2k_btag_hfstats1_up;
  TH1F *cos_theta2k_btag_hfstats1_down;
  TH1F *cos_theta2k_btag_hfstats2_up;
  TH1F *cos_theta2k_btag_hfstats2_down;
  TH1F *cos_theta2k_btag_lf_up;
  TH1F *cos_theta2k_btag_lf_down;
  TH1F *cos_theta2k_btag_lfstats1_up;
  TH1F *cos_theta2k_btag_lfstats1_down;
  TH1F *cos_theta2k_btag_lfstats2_up;
  TH1F *cos_theta2k_btag_lfstats2_down;
  TH1F *cos_theta2k_ttag_corr_up;
  TH1F *cos_theta2k_ttag_corr_down;
  TH1F *cos_theta2k_ttag_uncorr_up;
  TH1F *cos_theta2k_ttag_uncorr_down;
  TH1F *cos_theta2k_tmistag_up;
  TH1F *cos_theta2k_tmistag_down;
  TH1F *cos_theta2k_toppt_a_up;
  TH1F *cos_theta2k_toppt_a_down;
  TH1F *cos_theta2k_toppt_b_up;
  TH1F *cos_theta2k_toppt_b_down;
  TH1F *cos_theta2k_murmuf_upup;
  TH1F *cos_theta2k_murmuf_upnone;
  TH1F *cos_theta2k_murmuf_noneup;
  TH1F *cos_theta2k_murmuf_nonedown;
  TH1F *cos_theta2k_murmuf_downnone;
  TH1F *cos_theta2k_murmuf_downdown;
  TH1F *cos_theta2k_isr_up;
  TH1F *cos_theta2k_isr_down;
  TH1F *cos_theta2k_fsr_up;
  TH1F *cos_theta2k_fsr_down;

  // cos_theta2r
  TH1F *cos_theta2r_ele_reco_up;
  TH1F *cos_theta2r_ele_reco_down;
  TH1F *cos_theta2r_ele_id_up;
  TH1F *cos_theta2r_ele_id_down;
  TH1F *cos_theta2r_ele_trigger_up;
  TH1F *cos_theta2r_ele_trigger_down;
  TH1F *cos_theta2r_mu_reco_up;
  TH1F *cos_theta2r_mu_reco_down;
  TH1F *cos_theta2r_mu_id_stat_up;
  TH1F *cos_theta2r_mu_id_stat_down;
  TH1F *cos_theta2r_mu_id_syst_up;
  TH1F *cos_theta2r_mu_id_syst_down;
  TH1F *cos_theta2r_mu_trigger_stat_up;
  TH1F *cos_theta2r_mu_trigger_stat_down;
  TH1F *cos_theta2r_mu_trigger_syst_up;
  TH1F *cos_theta2r_mu_trigger_syst_down;
  TH1F *cos_theta2r_mu_iso_stat_up;
  TH1F *cos_theta2r_mu_iso_stat_down;
  TH1F *cos_theta2r_mu_iso_syst_up;
  TH1F *cos_theta2r_mu_iso_syst_down;
  TH1F *cos_theta2r_pu_up;
  TH1F *cos_theta2r_pu_down;
  TH1F *cos_theta2r_prefiring_up;
  TH1F *cos_theta2r_prefiring_down;
  TH1F *cos_theta2r_btag_cferr1_up;
  TH1F *cos_theta2r_btag_cferr1_down;
  TH1F *cos_theta2r_btag_cferr2_up;
  TH1F *cos_theta2r_btag_cferr2_down;
  TH1F *cos_theta2r_btag_hf_up;
  TH1F *cos_theta2r_btag_hf_down;
  TH1F *cos_theta2r_btag_hfstats1_up;
  TH1F *cos_theta2r_btag_hfstats1_down;
  TH1F *cos_theta2r_btag_hfstats2_up;
  TH1F *cos_theta2r_btag_hfstats2_down;
  TH1F *cos_theta2r_btag_lf_up;
  TH1F *cos_theta2r_btag_lf_down;
  TH1F *cos_theta2r_btag_lfstats1_up;
  TH1F *cos_theta2r_btag_lfstats1_down;
  TH1F *cos_theta2r_btag_lfstats2_up;
  TH1F *cos_theta2r_btag_lfstats2_down;
  TH1F *cos_theta2r_ttag_corr_up;
  TH1F *cos_theta2r_ttag_corr_down;
  TH1F *cos_theta2r_ttag_uncorr_up;
  TH1F *cos_theta2r_ttag_uncorr_down;
  TH1F *cos_theta2r_tmistag_up;
  TH1F *cos_theta2r_tmistag_down;
  TH1F *cos_theta2r_toppt_a_up;
  TH1F *cos_theta2r_toppt_a_down;
  TH1F *cos_theta2r_toppt_b_up;
  TH1F *cos_theta2r_toppt_b_down;
  TH1F *cos_theta2r_murmuf_upup;
  TH1F *cos_theta2r_murmuf_upnone;
  TH1F *cos_theta2r_murmuf_noneup;
  TH1F *cos_theta2r_murmuf_nonedown;
  TH1F *cos_theta2r_murmuf_downnone;
  TH1F *cos_theta2r_murmuf_downdown;
  TH1F *cos_theta2r_isr_up;
  TH1F *cos_theta2r_isr_down;
  TH1F *cos_theta2r_fsr_up;
  TH1F *cos_theta2r_fsr_down;

  // cos_theta2n
  TH1F *cos_theta2n_ele_reco_up;
  TH1F *cos_theta2n_ele_reco_down;
  TH1F *cos_theta2n_ele_id_up;
  TH1F *cos_theta2n_ele_id_down;
  TH1F *cos_theta2n_ele_trigger_up;
  TH1F *cos_theta2n_ele_trigger_down;
  TH1F *cos_theta2n_mu_reco_up;
  TH1F *cos_theta2n_mu_reco_down;
  TH1F *cos_theta2n_mu_id_stat_up;
  TH1F *cos_theta2n_mu_id_stat_down;
  TH1F *cos_theta2n_mu_id_syst_up;
  TH1F *cos_theta2n_mu_id_syst_down;
  TH1F *cos_theta2n_mu_trigger_stat_up;
  TH1F *cos_theta2n_mu_trigger_stat_down;
  TH1F *cos_theta2n_mu_trigger_syst_up;
  TH1F *cos_theta2n_mu_trigger_syst_down;
  TH1F *cos_theta2n_mu_iso_stat_up;
  TH1F *cos_theta2n_mu_iso_stat_down;
  TH1F *cos_theta2n_mu_iso_syst_up;
  TH1F *cos_theta2n_mu_iso_syst_down;
  TH1F *cos_theta2n_pu_up;
  TH1F *cos_theta2n_pu_down;
  TH1F *cos_theta2n_prefiring_up;
  TH1F *cos_theta2n_prefiring_down;
  TH1F *cos_theta2n_btag_cferr1_up;
  TH1F *cos_theta2n_btag_cferr1_down;
  TH1F *cos_theta2n_btag_cferr2_up;
  TH1F *cos_theta2n_btag_cferr2_down;
  TH1F *cos_theta2n_btag_hf_up;
  TH1F *cos_theta2n_btag_hf_down;
  TH1F *cos_theta2n_btag_hfstats1_up;
  TH1F *cos_theta2n_btag_hfstats1_down;
  TH1F *cos_theta2n_btag_hfstats2_up;
  TH1F *cos_theta2n_btag_hfstats2_down;
  TH1F *cos_theta2n_btag_lf_up;
  TH1F *cos_theta2n_btag_lf_down;
  TH1F *cos_theta2n_btag_lfstats1_up;
  TH1F *cos_theta2n_btag_lfstats1_down;
  TH1F *cos_theta2n_btag_lfstats2_up;
  TH1F *cos_theta2n_btag_lfstats2_down;
  TH1F *cos_theta2n_ttag_corr_up;
  TH1F *cos_theta2n_ttag_corr_down;
  TH1F *cos_theta2n_ttag_uncorr_up;
  TH1F *cos_theta2n_ttag_uncorr_down;
  TH1F *cos_theta2n_tmistag_up;
  TH1F *cos_theta2n_tmistag_down;
  TH1F *cos_theta2n_toppt_a_up;
  TH1F *cos_theta2n_toppt_a_down;
  TH1F *cos_theta2n_toppt_b_up;
  TH1F *cos_theta2n_toppt_b_down;
  TH1F *cos_theta2n_murmuf_upup;
  TH1F *cos_theta2n_murmuf_upnone;
  TH1F *cos_theta2n_murmuf_noneup;
  TH1F *cos_theta2n_murmuf_nonedown;
  TH1F *cos_theta2n_murmuf_downnone;
  TH1F *cos_theta2n_murmuf_downdown;
  TH1F *cos_theta2n_isr_up;
  TH1F *cos_theta2n_isr_down;
  TH1F *cos_theta2n_fsr_up;
  TH1F *cos_theta2n_fsr_down;

  // // cos_theta2kStar
  // TH1F *cos_theta2kStar_ele_reco_up;
  // TH1F *cos_theta2kStar_ele_reco_down;
  // TH1F *cos_theta2kStar_ele_id_up;
  // TH1F *cos_theta2kStar_ele_id_down;
  // TH1F *cos_theta2kStar_ele_trigger_up;
  // TH1F *cos_theta2kStar_ele_trigger_down;
  // TH1F *cos_theta2kStar_mu_reco_up;
  // TH1F *cos_theta2kStar_mu_reco_down;
  // TH1F *cos_theta2kStar_mu_id_stat_up;
  // TH1F *cos_theta2kStar_mu_id_stat_down;
  // TH1F *cos_theta2kStar_mu_id_syst_up;
  // TH1F *cos_theta2kStar_mu_id_syst_down;
  // TH1F *cos_theta2kStar_mu_trigger_stat_up;
  // TH1F *cos_theta2kStar_mu_trigger_stat_down;
  // TH1F *cos_theta2kStar_mu_trigger_syst_up;
  // TH1F *cos_theta2kStar_mu_trigger_syst_down;
  // TH1F *cos_theta2kStar_mu_iso_stat_up;
  // TH1F *cos_theta2kStar_mu_iso_stat_down;
  // TH1F *cos_theta2kStar_mu_iso_syst_up;
  // TH1F *cos_theta2kStar_mu_iso_syst_down;
  // TH1F *cos_theta2kStar_pu_up;
  // TH1F *cos_theta2kStar_pu_down;
  // TH1F *cos_theta2kStar_prefiring_up;
  // TH1F *cos_theta2kStar_prefiring_down;
  // TH1F *cos_theta2kStar_btag_cferr1_up;
  // TH1F *cos_theta2kStar_btag_cferr1_down;
  // TH1F *cos_theta2kStar_btag_cferr2_up;
  // TH1F *cos_theta2kStar_btag_cferr2_down;
  // TH1F *cos_theta2kStar_btag_hf_up;
  // TH1F *cos_theta2kStar_btag_hf_down;
  // TH1F *cos_theta2kStar_btag_hfstats1_up;
  // TH1F *cos_theta2kStar_btag_hfstats1_down;
  // TH1F *cos_theta2kStar_btag_hfstats2_up;
  // TH1F *cos_theta2kStar_btag_hfstats2_down;
  // TH1F *cos_theta2kStar_btag_lf_up;
  // TH1F *cos_theta2kStar_btag_lf_down;
  // TH1F *cos_theta2kStar_btag_lfstats1_up;
  // TH1F *cos_theta2kStar_btag_lfstats1_down;
  // TH1F *cos_theta2kStar_btag_lfstats2_up;
  // TH1F *cos_theta2kStar_btag_lfstats2_down;
  // TH1F *cos_theta2kStar_ttag_corr_up;
  // TH1F *cos_theta2kStar_ttag_corr_down;
  // TH1F *cos_theta2kStar_ttag_uncorr_up;
  // TH1F *cos_theta2kStar_ttag_uncorr_down;
  // TH1F *cos_theta2kStar_tmistag_up;
  // TH1F *cos_theta2kStar_tmistag_down;
  // TH1F *cos_theta2kStar_toppt_a_up;
  // TH1F *cos_theta2kStar_toppt_a_down;
  // TH1F *cos_theta2kStar_toppt_b_up;
  // TH1F *cos_theta2kStar_toppt_b_down;
  // TH1F *cos_theta2kStar_murmuf_upup;
  // TH1F *cos_theta2kStar_murmuf_upnone;
  // TH1F *cos_theta2kStar_murmuf_noneup;
  // TH1F *cos_theta2kStar_murmuf_nonedown;
  // TH1F *cos_theta2kStar_murmuf_downnone;
  // TH1F *cos_theta2kStar_murmuf_downdown;
  // TH1F *cos_theta2kStar_isr_up;
  // TH1F *cos_theta2kStar_isr_down;
  // TH1F *cos_theta2kStar_fsr_up;
  // TH1F *cos_theta2kStar_fsr_down;

  // // cos_theta2rStar
  // TH1F *cos_theta2rStar_ele_reco_up;
  // TH1F *cos_theta2rStar_ele_reco_down;
  // TH1F *cos_theta2rStar_ele_id_up;
  // TH1F *cos_theta2rStar_ele_id_down;
  // TH1F *cos_theta2rStar_ele_trigger_up;
  // TH1F *cos_theta2rStar_ele_trigger_down;
  // TH1F *cos_theta2rStar_mu_reco_up;
  // TH1F *cos_theta2rStar_mu_reco_down;
  // TH1F *cos_theta2rStar_mu_id_stat_up;
  // TH1F *cos_theta2rStar_mu_id_stat_down;
  // TH1F *cos_theta2rStar_mu_id_syst_up;
  // TH1F *cos_theta2rStar_mu_id_syst_down;
  // TH1F *cos_theta2rStar_mu_trigger_stat_up;
  // TH1F *cos_theta2rStar_mu_trigger_stat_down;
  // TH1F *cos_theta2rStar_mu_trigger_syst_up;
  // TH1F *cos_theta2rStar_mu_trigger_syst_down;
  // TH1F *cos_theta2rStar_mu_iso_stat_up;
  // TH1F *cos_theta2rStar_mu_iso_stat_down;
  // TH1F *cos_theta2rStar_mu_iso_syst_up;
  // TH1F *cos_theta2rStar_mu_iso_syst_down;
  // TH1F *cos_theta2rStar_pu_up;
  // TH1F *cos_theta2rStar_pu_down;
  // TH1F *cos_theta2rStar_prefiring_up;
  // TH1F *cos_theta2rStar_prefiring_down;
  // TH1F *cos_theta2rStar_btag_cferr1_up;
  // TH1F *cos_theta2rStar_btag_cferr1_down;
  // TH1F *cos_theta2rStar_btag_cferr2_up;
  // TH1F *cos_theta2rStar_btag_cferr2_down;
  // TH1F *cos_theta2rStar_btag_hf_up;
  // TH1F *cos_theta2rStar_btag_hf_down;
  // TH1F *cos_theta2rStar_btag_hfstats1_up;
  // TH1F *cos_theta2rStar_btag_hfstats1_down;
  // TH1F *cos_theta2rStar_btag_hfstats2_up;
  // TH1F *cos_theta2rStar_btag_hfstats2_down;
  // TH1F *cos_theta2rStar_btag_lf_up;
  // TH1F *cos_theta2rStar_btag_lf_down;
  // TH1F *cos_theta2rStar_btag_lfstats1_up;
  // TH1F *cos_theta2rStar_btag_lfstats1_down;
  // TH1F *cos_theta2rStar_btag_lfstats2_up;
  // TH1F *cos_theta2rStar_btag_lfstats2_down;
  // TH1F *cos_theta2rStar_ttag_corr_up;
  // TH1F *cos_theta2rStar_ttag_corr_down;
  // TH1F *cos_theta2rStar_ttag_uncorr_up;
  // TH1F *cos_theta2rStar_ttag_uncorr_down;
  // TH1F *cos_theta2rStar_tmistag_up;
  // TH1F *cos_theta2rStar_tmistag_down;
  // TH1F *cos_theta2rStar_toppt_a_up;
  // TH1F *cos_theta2rStar_toppt_a_down;
  // TH1F *cos_theta2rStar_toppt_b_up;
  // TH1F *cos_theta2rStar_toppt_b_down;
  // TH1F *cos_theta2rStar_murmuf_upup;
  // TH1F *cos_theta2rStar_murmuf_upnone;
  // TH1F *cos_theta2rStar_murmuf_noneup;
  // TH1F *cos_theta2rStar_murmuf_nonedown;
  // TH1F *cos_theta2rStar_murmuf_downnone;
  // TH1F *cos_theta2rStar_murmuf_downdown;
  // TH1F *cos_theta2rStar_isr_up;
  // TH1F *cos_theta2rStar_isr_down;
  // TH1F *cos_theta2rStar_fsr_up;
  // TH1F *cos_theta2rStar_fsr_down;
  
  // Ckk
  // Crr
  // Cnn
  // Crk_plus
  // Crk_minus
  // Cnr_plus
  // Cnr_minus
  // Cnk_plus
  // Cnk_minus

  // cHel_Mtt300_400
  TH1F *cHel_Mtt300_400_ele_reco_up;
  TH1F *cHel_Mtt300_400_ele_reco_down;
  TH1F *cHel_Mtt300_400_ele_id_up;
  TH1F *cHel_Mtt300_400_ele_id_down;
  TH1F *cHel_Mtt300_400_ele_trigger_up;
  TH1F *cHel_Mtt300_400_ele_trigger_down;
  TH1F *cHel_Mtt300_400_mu_reco_up;
  TH1F *cHel_Mtt300_400_mu_reco_down;
  TH1F *cHel_Mtt300_400_mu_id_stat_up;
  TH1F *cHel_Mtt300_400_mu_id_stat_down;
  TH1F *cHel_Mtt300_400_mu_id_syst_up;
  TH1F *cHel_Mtt300_400_mu_id_syst_down;
  TH1F *cHel_Mtt300_400_mu_trigger_stat_up;
  TH1F *cHel_Mtt300_400_mu_trigger_stat_down;
  TH1F *cHel_Mtt300_400_mu_trigger_syst_up;
  TH1F *cHel_Mtt300_400_mu_trigger_syst_down;
  TH1F *cHel_Mtt300_400_mu_iso_stat_up;
  TH1F *cHel_Mtt300_400_mu_iso_stat_down;
  TH1F *cHel_Mtt300_400_mu_iso_syst_up;
  TH1F *cHel_Mtt300_400_mu_iso_syst_down;
  TH1F *cHel_Mtt300_400_pu_up;
  TH1F *cHel_Mtt300_400_pu_down;
  TH1F *cHel_Mtt300_400_prefiring_up;
  TH1F *cHel_Mtt300_400_prefiring_down;
  TH1F *cHel_Mtt300_400_btag_cferr1_up;
  TH1F *cHel_Mtt300_400_btag_cferr1_down;
  TH1F *cHel_Mtt300_400_btag_cferr2_up;
  TH1F *cHel_Mtt300_400_btag_cferr2_down;
  TH1F *cHel_Mtt300_400_btag_hf_up;
  TH1F *cHel_Mtt300_400_btag_hf_down;
  TH1F *cHel_Mtt300_400_btag_hfstats1_up;
  TH1F *cHel_Mtt300_400_btag_hfstats1_down;
  TH1F *cHel_Mtt300_400_btag_hfstats2_up;
  TH1F *cHel_Mtt300_400_btag_hfstats2_down;
  TH1F *cHel_Mtt300_400_btag_lf_up;
  TH1F *cHel_Mtt300_400_btag_lf_down;
  TH1F *cHel_Mtt300_400_btag_lfstats1_up;
  TH1F *cHel_Mtt300_400_btag_lfstats1_down;
  TH1F *cHel_Mtt300_400_btag_lfstats2_up;
  TH1F *cHel_Mtt300_400_btag_lfstats2_down;
  TH1F *cHel_Mtt300_400_ttag_corr_up;
  TH1F *cHel_Mtt300_400_ttag_corr_down;
  TH1F *cHel_Mtt300_400_ttag_uncorr_up;
  TH1F *cHel_Mtt300_400_ttag_uncorr_down;
  TH1F *cHel_Mtt300_400_tmistag_up;
  TH1F *cHel_Mtt300_400_tmistag_down;
  TH1F *cHel_Mtt300_400_toppt_a_up;
  TH1F *cHel_Mtt300_400_toppt_a_down;
  TH1F *cHel_Mtt300_400_toppt_b_up;
  TH1F *cHel_Mtt300_400_toppt_b_down;
  TH1F *cHel_Mtt300_400_murmuf_upup;
  TH1F *cHel_Mtt300_400_murmuf_upnone;
  TH1F *cHel_Mtt300_400_murmuf_noneup;
  TH1F *cHel_Mtt300_400_murmuf_nonedown;
  TH1F *cHel_Mtt300_400_murmuf_downnone;
  TH1F *cHel_Mtt300_400_murmuf_downdown;
  TH1F *cHel_Mtt300_400_isr_up;
  TH1F *cHel_Mtt300_400_isr_down;
  TH1F *cHel_Mtt300_400_fsr_up;
  TH1F *cHel_Mtt300_400_fsr_down;

  // cHel_Mtt300_400_betaLT0p9
  TH1F *cHel_Mtt300_400_betaLT0p9_ele_reco_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_ele_reco_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_ele_id_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_ele_id_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_ele_trigger_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_ele_trigger_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_mu_reco_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_mu_reco_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_mu_id_stat_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_mu_id_stat_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_mu_id_syst_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_mu_id_syst_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_mu_trigger_stat_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_mu_trigger_stat_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_mu_trigger_syst_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_mu_trigger_syst_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_mu_iso_stat_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_mu_iso_stat_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_mu_iso_syst_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_mu_iso_syst_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_pu_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_pu_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_prefiring_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_prefiring_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_btag_cferr1_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_btag_cferr1_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_btag_cferr2_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_btag_cferr2_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_btag_hf_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_btag_hf_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_btag_hfstats1_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_btag_hfstats1_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_btag_hfstats2_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_btag_hfstats2_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_btag_lf_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_btag_lf_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_btag_lfstats1_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_btag_lfstats1_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_btag_lfstats2_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_btag_lfstats2_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_ttag_corr_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_ttag_corr_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_ttag_uncorr_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_ttag_uncorr_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_tmistag_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_tmistag_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_toppt_a_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_toppt_a_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_toppt_b_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_toppt_b_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_murmuf_upup;
  TH1F *cHel_Mtt300_400_betaLT0p9_murmuf_upnone;
  TH1F *cHel_Mtt300_400_betaLT0p9_murmuf_noneup;
  TH1F *cHel_Mtt300_400_betaLT0p9_murmuf_nonedown;
  TH1F *cHel_Mtt300_400_betaLT0p9_murmuf_downnone;
  TH1F *cHel_Mtt300_400_betaLT0p9_murmuf_downdown;
  TH1F *cHel_Mtt300_400_betaLT0p9_isr_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_isr_down;
  TH1F *cHel_Mtt300_400_betaLT0p9_fsr_up;
  TH1F *cHel_Mtt300_400_betaLT0p9_fsr_down;

  // cHel_P3n_Mtt800_Inf
  TH1F *cHel_P3n_Mtt800_Inf_ele_reco_up;
  TH1F *cHel_P3n_Mtt800_Inf_ele_reco_down;
  TH1F *cHel_P3n_Mtt800_Inf_ele_id_up;
  TH1F *cHel_P3n_Mtt800_Inf_ele_id_down;
  TH1F *cHel_P3n_Mtt800_Inf_ele_trigger_up;
  TH1F *cHel_P3n_Mtt800_Inf_ele_trigger_down;
  TH1F *cHel_P3n_Mtt800_Inf_mu_reco_up;
  TH1F *cHel_P3n_Mtt800_Inf_mu_reco_down;
  TH1F *cHel_P3n_Mtt800_Inf_mu_id_stat_up;
  TH1F *cHel_P3n_Mtt800_Inf_mu_id_stat_down;
  TH1F *cHel_P3n_Mtt800_Inf_mu_id_syst_up;
  TH1F *cHel_P3n_Mtt800_Inf_mu_id_syst_down;
  TH1F *cHel_P3n_Mtt800_Inf_mu_trigger_stat_up;
  TH1F *cHel_P3n_Mtt800_Inf_mu_trigger_stat_down;
  TH1F *cHel_P3n_Mtt800_Inf_mu_trigger_syst_up;
  TH1F *cHel_P3n_Mtt800_Inf_mu_trigger_syst_down;
  TH1F *cHel_P3n_Mtt800_Inf_mu_iso_stat_up;
  TH1F *cHel_P3n_Mtt800_Inf_mu_iso_stat_down;
  TH1F *cHel_P3n_Mtt800_Inf_mu_iso_syst_up;
  TH1F *cHel_P3n_Mtt800_Inf_mu_iso_syst_down;
  TH1F *cHel_P3n_Mtt800_Inf_pu_up;
  TH1F *cHel_P3n_Mtt800_Inf_pu_down;
  TH1F *cHel_P3n_Mtt800_Inf_prefiring_up;
  TH1F *cHel_P3n_Mtt800_Inf_prefiring_down;
  TH1F *cHel_P3n_Mtt800_Inf_btag_cferr1_up;
  TH1F *cHel_P3n_Mtt800_Inf_btag_cferr1_down;
  TH1F *cHel_P3n_Mtt800_Inf_btag_cferr2_up;
  TH1F *cHel_P3n_Mtt800_Inf_btag_cferr2_down;
  TH1F *cHel_P3n_Mtt800_Inf_btag_hf_up;
  TH1F *cHel_P3n_Mtt800_Inf_btag_hf_down;
  TH1F *cHel_P3n_Mtt800_Inf_btag_hfstats1_up;
  TH1F *cHel_P3n_Mtt800_Inf_btag_hfstats1_down;
  TH1F *cHel_P3n_Mtt800_Inf_btag_hfstats2_up;
  TH1F *cHel_P3n_Mtt800_Inf_btag_hfstats2_down;
  TH1F *cHel_P3n_Mtt800_Inf_btag_lf_up;
  TH1F *cHel_P3n_Mtt800_Inf_btag_lf_down;
  TH1F *cHel_P3n_Mtt800_Inf_btag_lfstats1_up;
  TH1F *cHel_P3n_Mtt800_Inf_btag_lfstats1_down;
  TH1F *cHel_P3n_Mtt800_Inf_btag_lfstats2_up;
  TH1F *cHel_P3n_Mtt800_Inf_btag_lfstats2_down;
  TH1F *cHel_P3n_Mtt800_Inf_ttag_corr_up;
  TH1F *cHel_P3n_Mtt800_Inf_ttag_corr_down;
  TH1F *cHel_P3n_Mtt800_Inf_ttag_uncorr_up;
  TH1F *cHel_P3n_Mtt800_Inf_ttag_uncorr_down;
  TH1F *cHel_P3n_Mtt800_Inf_tmistag_up;
  TH1F *cHel_P3n_Mtt800_Inf_tmistag_down;
  TH1F *cHel_P3n_Mtt800_Inf_toppt_a_up;
  TH1F *cHel_P3n_Mtt800_Inf_toppt_a_down;
  TH1F *cHel_P3n_Mtt800_Inf_toppt_b_up;
  TH1F *cHel_P3n_Mtt800_Inf_toppt_b_down;
  TH1F *cHel_P3n_Mtt800_Inf_murmuf_upup;
  TH1F *cHel_P3n_Mtt800_Inf_murmuf_upnone;
  TH1F *cHel_P3n_Mtt800_Inf_murmuf_noneup;
  TH1F *cHel_P3n_Mtt800_Inf_murmuf_nonedown;
  TH1F *cHel_P3n_Mtt800_Inf_murmuf_downnone;
  TH1F *cHel_P3n_Mtt800_Inf_murmuf_downdown;
  TH1F *cHel_P3n_Mtt800_Inf_isr_up;
  TH1F *cHel_P3n_Mtt800_Inf_isr_down;
  TH1F *cHel_P3n_Mtt800_Inf_fsr_up;
  TH1F *cHel_P3n_Mtt800_Inf_fsr_down;

  // cHel_P3n_Mtt800_Inf_cosThetaLT0p4
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_ele_reco_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_ele_reco_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_ele_id_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_ele_id_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_ele_trigger_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_ele_trigger_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_mu_reco_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_mu_reco_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_mu_id_stat_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_mu_id_stat_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_mu_id_syst_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_mu_id_syst_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_mu_trigger_stat_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_mu_trigger_stat_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_mu_trigger_syst_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_mu_trigger_syst_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_mu_iso_stat_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_mu_iso_stat_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_mu_iso_syst_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_mu_iso_syst_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_pu_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_pu_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_prefiring_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_prefiring_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_btag_cferr1_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_btag_cferr1_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_btag_cferr2_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_btag_cferr2_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_btag_hf_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_btag_hf_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_btag_hfstats1_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_btag_hfstats1_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_btag_hfstats2_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_btag_hfstats2_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_btag_lf_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_btag_lf_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_btag_lfstats1_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_btag_lfstats1_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_btag_lfstats2_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_btag_lfstats2_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_ttag_corr_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_ttag_corr_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_ttag_uncorr_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_ttag_uncorr_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_tmistag_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_tmistag_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_toppt_a_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_toppt_a_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_toppt_b_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_toppt_b_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_murmuf_upup;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_murmuf_upnone;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_murmuf_noneup;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_murmuf_nonedown;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_murmuf_downnone;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_murmuf_downdown;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_isr_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_isr_down;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_fsr_up;
  TH1F *cHel_P3n_Mtt800_Inf_cosThetaLT0p4_fsr_down;


  uhh2::Event::Handle< std::vector<TopJet> > h_AK8TopTags;
  uhh2::Event::Handle< std::vector<Jet> > h_CHSjets_matched;
  uhh2::Event::Handle<bool> h_is_zprime_reconstructed_chi2;
  uhh2::Event::Handle<ZprimeCandidate*> h_BestZprimeCandidateChi2;
  uhh2::Event::Handle<std::vector<ReconstructionHypothesis>> h_ttbar_hyps;

  // --- NoAC support for tanh systematics (TT-only) ---
  bool use_noac_evtweights_ = false;
  std::string noac_gen_file_;
  std::string noac_gen_hist_;
  double noac_fraction_ = 0.0;
  uhh2::Event::Handle<float> h_xi_gen;
  std::unique_ptr<TH1D> noac_weights_;

  static std::unique_ptr<TH1D> mirror_hist_1d(const TH1D &src);
  static std::unique_ptr<TH1D> build_noac_weights_from_gen(const TH1D &Hgen, double f_noac);
  static double lookup_noac_weight(const TH1 *W, double xi);
  
  // Template-method (xi) multi-f infrastructure
  std::vector<float> f_values;
  static std::map<float, std::unique_ptr<TH1D>> noac_weights_map;  // Static: shared across all instances
  static bool noac_weights_initialized;  // Flag to track if weights have been initialized
  std::map<std::string, TH1F*> h_deltaY_xi_reco_map;
  virtual ~ZprimeSemiLeptonicSystematicsHists();
};